### ISSUE TITLE
unassigned fibers RA, dec, x, y

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#109]
Unassigned, stuck, and broken fibers should still set meaningful RA, DEC, X, and Y quantities rather than NaN.  This will require implementing the conversion from (x,y + telra,teldec) -> (RA,DEC)

desitarget will soon define a NO_TARGET bit which should be set for DESI_TARGET for these fibers.

A new FIBERMASK column should be included in the output, setting bits for broken and stuck fibers (instead of resetting DESI_TARGET bits as it currently does).  See desihub/desispec#485.

**Comment by forero** [comment]
solved in #112
