### ISSUE TITLE
robustness to user error on input file formats

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#113]
fiberassign requires several input files, some of which need to be text and others are fits.  e.g. --footprint is the $DESIMODEL/data/footprint/desi-tiles.fits file (not the desi-tiles.txt file) but --positioners is the $DESIMODEL/data/focalplane/fiberpos.txt (not the fiberpos.fits file).

If you get the combination correct, it all works fine.  If you accidentally substitute a fits file for a text file (and possibly vice-a-versa) the code hangs using 0% CPU but not finishing.  It would be helpful if the I/O was more robust to crash more obviously on bad inputs.

This is low priority, and it is trying to save the user from themselves, but filing a ticket anyway...

**Comment by tskisner** [comment]
@forero notes that these types of checks could be more easily done in the python wrapper.

**Comment by sbailey** [comment]
Another example (from desihub/desitest#9): the fiberassign interface has now changed such that it requires the fiberpos-all.fits file, not the fiberpos.txt file.  If you give it the fiberpos.txt file (which used to work) it dies in an astropy I/O routine, and if you give it the fiberpos.fits file (which we thought would work) it runs and exits with 0 and no error messages but fails to write output because it couldn't find any ETC (sky monitor) fibers to position.

**Comment by tskisner** [comment]
This ticket is made obsolete by the recent code refactor.  Closed by 3beff2b8d484233fd705b33021e7f6972f11dcc2
