### ISSUE TITLE
extract standards from the input merged target list

### ISSUE THREAD

**Issue by moustakas** [desihub/fiberassign#120]
Related to https://github.com/desihub/desitarget/issues/256, and with #114 and #116 now complete, can't `fiberassign` extract the standard stars from the input `mtl.fits` file itself?  This change should simplify the fiber-assignment code and also make it simpler to run fiber assignment on a "real" target catalog (which doesn't generate a separate, duplicate catalog of standards).

**Comment by sbailey** [comment]
+1 .  It was an oversight that we didn't already have a ticket for this.  I'll remove the "question" flag from this to flag it as something to do.

The original motivation for having the standards in a separate file was to simplify re-using standards with different input mocks, so it would be convenient to retain that as an option, but move the default to extracting the standards directly from the same mtl file as the science targets.  For real data, many of the standards are real MWS targets anyway.

**Comment by tskisner** [comment]
The code now accepts an arbitrary number of target catalogs containing targets of any type.  The DESI_TARGET column and a user-defined (or default) bitmask is used to determine the type(s) of each target.  Closed by 3beff2b8d484233fd705b33021e7f6972f11dcc2
