### ISSUE TITLE
failing to assign standard stars

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#130]
@forero can you help with this?  This is a blocking factor for the next (and overdue) software release.

The following command fails to assign any standard stars:
```
fiberassign  \
--mtl /global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/mtl.fits \
--stdstar /global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/standards-dark.fits \
--sky /global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/sky.fits \
--surveytiles /global/cscratch1/sd/sjbailey/desi/dev/end2end/fiberassign/dark-tiles.txt \
--fibstatusfile /global/cscratch1/sd/sjbailey/desi/code/desitest/mini/fiberstatus.ecsv \
--outdir $SCRATCH/temp/

qa-fiberassign $SCRATCH/temp/tile*.fits
```

The input files have standard stars, they seem to have the right targeting bits set, but somewhere they get dropped.

This is a spin off from desihub/desitest#9 .

**Comment by forero** [comment]
I am taking a look at this right now.

**Comment by forero** [comment]
@sbailey There was indeed a bug (an overflowing int at the moment of initializing the `SS` flag). Please test the bugfix in branch `debug`.

**Comment by weaverba137** [comment]
I am testing this now.

**Comment by sbailey** [comment]
This appears to be a normal level of "not quite enough" standard stars due to the current default standard star density.  Let's proceed with the fiberassign PR.
