### ISSUE TITLE
prioritizing multiple fiber assignments for targets in SV

### ISSUE THREAD

**Issue by kdawson1000** [desihub/fiberassign#133]
We will need to increase the number of fiber assignments per object during survey validation.  The goal is to have a target assigned a fiber four times before another available target is given a fiber.

In the test runs on the BGS survey validation fields, no object is assigned a fiber more than once.  

Can we change the prioritization such that an object is prioritized for four total fiber assignment before another target is assigned in its place?  This should be done similar to the multiple-epoch quasar fiber assignment.

**Comment by sbailey** [comment]
The "Merged Target List" inputs to fiberassign have a NUMOBS_MORE column for how many more times it is requested to be observed and fiberassign will try to meet that given the tile/fiber overlaps available.  Higher PRIORITY+SUBPRIORITY targets get placed first.  This can be set independently per target.

i.e. I think that provides the flexibility needed for SV.  If not, please clarify what is missing.

**Comment by forero** [comment]
The MTL is generated using a function from desitarget
    `mtl = desitarget.mtl.make_mtl(targetdata)`
https://github.com/forero/fiberassign_sv/blob/master/main.py#L107

NUMOBS is computed there. Full details are here
https://github.com/desihub/desitarget/blob/master/py/desitarget/targets.py#L417

The fix in this case would be changing by hand that column in the mtl file.  I don't think there is anything to change in fiberassign.

**Comment by sbailey** [comment]
I'm going to close this ticket since I think it is just a matter of how to use the existing features, but feel free to re-open or submit a new ticket if it turns out that we need additional fiberassign functionality to support this for SV.

**Comment by rncahn** [comment]
I agree.  The capability is in fiberassign.  This is the same capability
needed for multiple observations of QSOs, LRGs.
