### ISSUE TITLE
Avoid dropping science targets for sky fibres if alternate sky locations are available?

### ISSUE THREAD

**Issue by apcooper** [desihub/fiberassign#134]
Following up on an offline query to @forero. 

There may be petals where both these are true:
 * More than the minimum number of fibres are assigned to sky, because some fibres don't have a science target.
 * Some of the sky fibres we assigned to meet the minimum requirements are blocking a science target.

In those cases we might consider swapping science-blocking 'mandatory' sky fibres back to science targets, so long as the minimum number requirement is satisfied.

I'm not pushing for this, we just wanted to bring it up for consideration. Possible negatives: gains might be small; distribution of sky fibres would depend weakly on the (total) target density, likewise the probability of a science target being dropped in favour of a sky fibre.

**Comment by forero** [comment]
@apcooper The gains can be quantified by taking a look at the `POTENTIAL` table in the tile files (The table lists all the potential targets available for every fiber). Do you volunteer to take a look at that?

**Comment by rncahn** [comment]
Andrew,

I suspect the effect is really, really small.  Assigning sky fibers is done
after assigning real targets.

Bob

**Comment by forero** [comment]
@rncahn Oh! My understanding of the code was that stars+sky were assigned first. If science targets come first and then pushed to fill stars+sky then the effect should be small.

**Comment by apcooper** [comment]
> @apcooper The gains can be quantified by taking a look at the POTENTIAL table in the tile files (The table lists all the potential targets available for every fiber). Do you volunteer to take a look at that?

If you can direct me to some recent enough reference outputs, I can take a look.

> My understanding of the code was that stars+sky were assigned first. If science targets come first and then pushed to fill stars+sky then the effect should be small.

Would be good to know the definitive answer to this.

**Comment by forero** [comment]
@apcooper Here are some outputs http://portal.nersc.gov/project/desi/users/forero/SV_BGS_v0.2/.

**Comment by moustakas** [comment]
It came up on a recent Data Systems call (2018-July-24) in the context of discussion Survey Validation, that standard stars and sky fibers should be assigned *before* science targets, to ensure that the desired/required target density of calibrators is achieved.

Is this right?  If so, we should spin this into its own (high-priority) issue.

**Comment by forero** [comment]
The desired/required target density of calibrators is always achieved (provided there are enough of them, of course). See the discussion in #82.

**Comment by sbailey** [comment]
The assignment algorithm is:
1. assign science targets first.
2. assign sky and standards to unassigned fibers.
3. start stealing fibers from the lowest priority science targets only if needed to achieve the required std/sky densities.

i.e. the case that @apcooper described in the initial post should never happen (higher sky density than required while still bumping science targets).  Was that concern theoretical or do you have a specific example of that happening (in which case it is a fiberassign bug)?  If you have an example, please post details.  Otherwise I'd like to close this ticket.

**Comment by apcooper** [comment]
Thanks for the explanation, @sbailey. The concern was theoretical. Happy to close.

I looked briefly at @forero's example run but was confused by the 80 standards and 1285 skies per tile. I'll follow that up with @forero separately.

**Comment by forero** [comment]
@apcooper A high number of skies per tile can happen if the science target density is low. That can be checked using the `POTENTIAL` field in the output `fiberassign` files.
