### ISSUE TITLE
Number of standars and sky per petal as input parameter

### ISSUE THREAD

**Issue by forero** [desihub/fiberassign#135]
The current version of `fiberassign` has hardcoded numbers for the number of standard stars and sky fibers per petal. This should be instead set as an input parameter, the current values should be used as default.

**Comment by sbailey** [comment]
Flagging as an "onsky" issue because we will need this flexibility for commissioning, even though we could literally go on sky without having this as a on-the-fly configurable parameter.

**Comment by forero** [comment]
Solved in this commit https://github.com/desihub/fiberassign/commit/c1fcdfeec0322198609b74def2259e7964d694dc

I pushed directly to master by mistake!
@sbailey @rncahn  please help me running more tests. I ran some simple tests and it works as expected.
