### ISSUE TITLE
where is subpriority used (if at all)?

### ISSUE THREAD

**Issue by moustakas** [desihub/fiberassign#137]
Apologies for my unfamiliarity with the `fiberassign` code, which I'm trying to learn.  

Where is `subpriority` used, if at all?  It looks like this field is [documented](https://desidatamodel.readthedocs.io/en/latest/DESI_TARGET/mtl.html?highlight=subpriority) in the data model but not written out by [`desitarget.mtl.make_mtl`](https://github.com/desihub/desitarget/blob/master/py/desitarget/mtl.py#L17) and not used (as far as I can tell) by `fiberassign`.  

Thanks in advance.

**Comment by rncahn** [comment]
Subpriority is used to choose between targets that otherwise have the same
priority.  It was introduced to replace throwing random numbers every time
such a choice needed to be made.  This provides for reproducibility while
avoiding biases that could creep in.

**Comment by moustakas** [comment]
Thanks @rncahn! Can you point me where specifically in the code subpriority
is used?

**Comment by rncahn** [comment]
In global.cpp, to determine which target to use:

inline int find_best (int j, int k, const MTL & M, const Plates & P,
const FP & pp, const Feat & F,
const Assignment & A) {
int best = -1;
int mbest = -1;
int pbest = 0;
double subpbest = 0.;
List av_gals = P[j].av_gals[k];
// For all available galaxies
for (size_t gg = 0; gg < av_gals.size(); gg++) {
int g = av_gals[gg];
// if(ok_for_limit_SS_SF(g,j,k,M,P,pp,F)){//don't assign SS, SF with
// find_best 11/20/15
if (!M[g].SS && !M[g].SF) {
// Check whether it needs further observation
int m = M[g].nobs_remain;
if (m >= 1) {
int prio = M[g].t_priority;
double subprio = M[g].subpriority;
// Takes it if better priority, or if same, if it needs more
// observations,
// so shares observations if two QSOs are close
// If still tied, use subpriority
if ( (prio > pbest) || ( (prio == pbest) && (m > mbest) ) ||
( ( prio == pbest) && ( m == mbest) &&
( subprio > subpbest) ) ) {
// Check that g is not assigned yet on this plate, or on
// the InterPlate around, check with ok_to_assign
int isa = A.is_assigned_jg(j, g, M, F);
int ok = ok_assign_g_to_jk(g, j, k, P, M, pp, F, A);
if ( (isa == -1) && ok) {
best = g;
pbest = prio;
mbest = m;
subpbest = subprio;
}
}
}
}
}
return best;

**Comment by moustakas** [comment]
Thanks @rncahn!

**Comment by sbailey** [comment]
More info: SUBPRIORITY is generated once at the time of target selection and written into the target catalog and then never changed.  MTL just propagates that forward along with the rest of the target catalog columns, which is why you don't see it in the MTL code.
