### ISSUE TITLE
fiberassign tests can only be run at NERSC

### ISSUE THREAD

**Issue by moustakas** [desihub/fiberassign#142]
The `test/test_fiberassign` tests (and perhaps others) use the parameter file `test/params_fiberassign.txt`, which has hard-coded NERSC paths.  It would be great to be able to test changes to the code in a machine-agnostic way, e.g., by keeping the "lite" MTL, SKY, etc. files in the fiberassign repository itself.

**Comment by tskisner** [comment]
The unit tests have been rewritten and now create fake target catalogs, write them out, read them back in, and verify that the resulting assignment has the expected number of science / standard / sky.  Closed by 3beff2b8d484233fd705b33021e7f6972f11dcc2
