### ISSUE TITLE
Refactor:  Final file format

### ISSUE THREAD

**Issue by tskisner** [desihub/fiberassign#159]
The "FIBERASSIGN" HDU of the final, merged FITS file should match the 18.12 reference release exactly, so that these outputs can be used as a drop-in replacement for downstream tools and to meet the ICD with online systems.  Additional data generated by the assignment process can be kept as extra HDUs.

**Comment by tskisner** [comment]
Additional note:  ensure that we are filling DESIGN_X/Y, DESIGN_Q/S, etc columns and ensure that unassigned fibers are given a fake target ID.  In offline discussion, it was proposed to use a negative ID value composed of the tile and fiber IDs for such unassigned fibers.

**Comment by tskisner** [comment]
Also ensure that GFA info is propagated to final output...

**Comment by sbailey** [comment]
Compared to master, the tsk_refactor branch output format has a superset of HDUs, a superset of columns, the same header keywords, and the correct number of rows.  Closing.
