### ISSUE TITLE
features files should support comments

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#17]
I tried commenting a line in a features file in order to replace it with a different one, which resulted in a segfault after ~20 minutes of calculations.  e.g. this doesn't work:
```
galFile /project/projectdirs/desi/mocks/preliminary/objects_ss_sf0.rdzipn
tileFile /project/projectdirs/desi/software/edison/desimodel/0.3.1/data/footprin
t/desi-tiles.par
fibFile /project/projectdirs/desi/software/edison/desimodel/0.3.1/data/focalplan
e/fiberpos.txt
# outDir /project/projectdirs/desi/users/rncahn/fa_output/
outDir /global/cscratch1/sd/sjbailey/fiberassign
SStarsfile /project/projectdirs/desi/mocks/preliminary/SStarsfile.txt
SkyFfile  /project/projectdirs/desi/mocks/preliminary/SkyFfile.txt
...
```

1. Features files should support comments
2. If the code can't parse a features file, it should stop immediately rather than leave uninitialized variables or whatever caused the much later crash.  Fail early, fail often.

**Comment by weaverba137** [comment]
Have we just surreptitiously introduced a new type of data file into DESI?  I have never heard of "feature" files.  Where are these documented?

**Comment by sbailey** [comment]
fiberassign is behind the curve on following standards.  It's not so much that a new format was surreptitiously introduced, as just that several custom formats from the old original code have not yet been removed.  We've been actively working on updating the *data* formats to use fits instead of custom binary and text formats.  The "features" file is a parameter config file.  Anyone is welcome to contribute to updating the C++ code to use a more standard text format for the input parameters.

I'll pre-emptively veto JSON since it also doesn't allow comments.

**Comment by weaverba137** [comment]
OK, thanx for the explanation.  I think cfg/ini files would be reasonable, since they allow comments, and we already make use of them in Python code.
