### ISSUE TITLE
legacy: TARGETS HDU is wrong

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#173]
As discovered by @tskisner in #165, the TARGETS HDU in the legacy (currently master) branch is wrong.

e.g. using `/global/cscratch1/sd/sjbailey/desi/fiberassign/refactor/master/tile-26819.fits`, targetid 607248736095043610 is a sky target assigned to fiber 19 at RA,DEC = 135.385269463, 11.1659706681; but in the TARGETS HDU that same TARGETID is claimed to be a MWS_ANY target at a different RA,DEC = 137.116582202, 11.8750876274.  Comparing back to the original inputs targets and skies, file, this is indeed a sky not a MWS_ANY target.

So far we only know of cases impacting SKY fibers being incorrectly labeled as science targets with the wrong location, but we haven't searched for the reverse.

For now let's keep focused on converging the tsk_refactor branch, but I'm opening this ticket for the record about this problem in the legacy branch too.

**Comment by tskisner** [comment]
This has been resolved for a long time.  Closing.
