### ISSUE TITLE
Positioner geometry consistency

### ISSUE THREAD

**Issue by tskisner** [desihub/fiberassign#178]
The current positioner geometry does not match what is used by the online systems for evaluating fiber collisions.  We should either read the equivalent data files used by that code, or (if the format is not suitable) we should collect all the needed info and define a new file format.

**Comment by sbailey** [comment]
Several items related to this that we may spin out to separate tickets when we are ready to implement them:
* coordinating file format with positioner testing and ICS
* tracking history of our knowledge of positioner geometry, and supporting mid-survey changes, e.g. if a petal is replaced
* supporting per-positioner arm lengths (current code treats all positioners as identical)
* supporting per-positioner max allowed radius (currently code uses 5.8mm for everyone; we may want to restrict "sticky" positioners to a smaller radius in case they get permanently stuck)
* consistency of exclusion polygons and code for collision calculations

**Comment by tskisner** [comment]
Fiberassign now uses a detailed, realistic hardware model from desimodel.  The desimodel code includes all these features and is external to fiberassign.  Closing this now.  Any issues with hardware state matching the online system (for example) should be opened against desimodel.
