### ISSUE TITLE
Handling of targets that are both science and standards

### ISSUE THREAD

**Issue by tskisner** [desihub/fiberassign#180]
I am opening this issue as a stand-alone ticket, but it touches on #140 and #165 and other issues as well.

Background
---------------------
We have some target IDs that are used as "science" targets during bright observations and "standards" during dark / gray observations.  These targets typically exist in multiple input catalogs with the same TARGETID and RA / DEC.  However, in different catalogs these duplicate targets could have different DESI_TARGET and OBSCONDITIONS values.  We want to use these targets as science targets for bright tiles and as standards for dark / gray tiles.

Current Situation
----------------------------
TARGETID values are required to be unique.  When the fiberassign code reads in a duplicate target, it checks that the RA/DEC values match.  Then it does the following:

    https://github.com/desihub/fiberassign/blob/master/src/targets.cpp#L139

- Bitwise OR the internal type (science, standard, sky)

- Bitwise OR the DESI_TARGET values

- Select the larger of the PRIORITY and SUBPRIORITY values

- Select the larger of the obs remaining

- Bitwise OR the OBSCONDITIONS

When initially implementing this behavior, I did not appreciate the implications of bitwise OR'ing the obsconditions.  This has the side effect of saying that, *"this target is both a science and a standard and is valid for all bright, dark, and gray tiles"*.  Clearly this is not the desired behavior- we want this target to be treated as a science target **only** on bright tiles and a standard **only** on dark / gray tiles.  @sbailey , I believe this may explain your difference of behavior when assigning all tiles together vs assigning bright separately from dark / gray. 

Possible Solutions
--------------------------------
There are several options to resolve this:

- (Workaround) Assign bright tiles separately from dark / gray, and pass the same target differently into those runs (pass it as a science target when assigning bright and as a standard when assigning dark / gray).  This just avoids the issue but does not solve the problem.

- Use a different TARGETID when treating a bright tile science object as a standard (e.g. take the TARGETID and add a large constant to get the fake TARGETID).  This would allow separately specifying the OBSCONDITIONS for the 2 targets.  The code should be changed to raise an exception for any duplicate TARGETID.

- Change the code logic.  When computing the available targets for a given tile, the code could use the meaning of the obsconditions bits to determine if this is a dark / gray tile and force the treatment of any "dual" targets to be only considered as a standard.  I do not like this solution since it makes the code more fragile to future changes.  Currently targets are considered for a tile based on simply bitwise AND'ing the tile and target obsconditions.

**Comment by geordie666** [comment]
@tskisner: One possibility. We have 4 remaining "reserved" bits in the `TARGETID`:

https://github.com/desihub/desitarget/blob/master/py/desitarget/data/targetmask.yaml#L144-L150

I'm going to need one of those to designate a secondary target. But, that leaves 3 bits. We could use one of those 3 remaining bits to distinguish something as a "standard". With careful use of the routines for encoding and decoding `TARGETID`:

https://github.com/desihub/desitarget/blob/master/py/desitarget/targets.py#L128-L129
https://github.com/desihub/desitarget/blob/master/py/desitarget/targets.py#L239-L240

it should then be possible for something to be treated as identical or not identical depending on how many bits are encoded or decoded. I'm not sure I'd want to set the "standard" bit during target selection, but you could re-code the `TARGETID` during fiber assignment?

I think this basically corresponds to your second option, but borrowing existing code from `desitarget.targets`.

**Comment by tskisner** [comment]
Ok, rephrasing your proposal (I think):

-  When loading catalogs and encountering a duplicate TARGETID, verify that the 2 obsconditions do not overlap.  If this is true, create an internal fake target with the new properties and store the fake <--> real mapping.  The obsconditions check ensures that the 2 targets will never be available on the same tile, and will internally be treated separately during assignment.

-  When writing out results, the only change that is needed is the re-map the fake target ID back to the original.  Since these 2 flavor of the same target are never on the same tile, everything works without any further modification.

I will not implement anything until next week, but this seems like an easy and promising idea.

**Comment by geordie666** [comment]
Yes, that's what I'm thinking.

Feel free to update

https://github.com/desihub/desitarget/blob/master/py/desitarget/data/targetmask.yaml#L144-L150
https://github.com/desihub/desitarget/blob/master/py/desitarget/targets.py#L128-L129
https://github.com/desihub/desitarget/blob/master/py/desitarget/targets.py#L239-L240

To steal the next bit for a "standard (used to resolve some cases in fiber assignment)". Or, ask me to do it and I can put some cycles in early next week.

I like reserving a specific bit throughout desihub to make `TARGETID` more traceable.

**Comment by kdawson1000** [comment]
I am reading this thread now.  I must confess that the proposed solution is not totally clear to me, so take my following comment with a grain of salt.

My impression is that these sorts of issues arise when a target falls into the Bright time program in a different way than it falls into the dark time program.  Other similar cases may also appear.  I think the MTL code is what causes objects to get bumped to higher priority when not intended.  I can imagine other cases arising (std stars getting observed in dark time and getting de-prioritized in bright time due to NOBS_MORE=0 condition).

My suggestion is to build the logic into the MTL code to independently assess the bright time fields and the dark time fields, and to run the fiber assignments independently.

I believe that any of these proposals will also collide with the discussion on how to deal with observations of the LRG sample between bright and dark time tiles.

**Comment by tskisner** [comment]
Hi @kdawson1000 and @sbailey, there are 2 issues that are interconnected on this ticket.  And actually the "workaround" mentioned in my original post was incomplete (see below):

1.  The fiberassign code should not be mucking around with merging targets that arrive from different files that have some duplicate information.  The upstream code should be responsible for providing a unique TARGETID with a correct obsconditions bitfield.  Fiberassign should raise an exception if it gets duplicate target IDs.  I think in practice we don't do this anymore- it was a feature of old target catalogs.  It is safe to change the code to enforce this.

2.  Separate from the previous point, there are some targets that genuinely have obsconditions bits set for both dark/gray and bright.  And they also have a DESI_TARGET value that (when used with the default bit masks) indicates that they are both a science target and a standard.  However, in these cases the same object is really being treated as a different type of target in the two cases.  Note that it is not sufficient to just run the dark/gray tiles separately from the bright tiles (I was wrong in my original post).  One also needs to pass different bitmasks to apply to DESI_TARGET.

Just to re-iterate / expand on this second point
------------------------------------------------------------------

A single target ID has a fixed DESI_TARGET value and obsconditions bitmask.  For a single run of fiberassign, a fixed bitmask is applied to DESI_TARGET to determine whether a target is treated as science, standard, sky.  There is not a separate bitmask for bright vs dark / gray.  The default bitmasks:

https://github.com/desihub/fiberassign/blob/master/py/fiberassign/targets.py#L49

will always treat BGS / MWS targets as "science" for **all** tiles matching its obsconditions and if the object has one of the standards bits raised:

https://github.com/desihub/fiberassign/blob/master/py/fiberassign/targets.py#L61

it will also **always** be treated as a standard for all tiles matching its obsconditions.  This is not what we want.

Solutions
----------------

1.  If we use a single TARGETID, DESI_TARGET value, and obsconditions in the input catalogs, then we must run fiberassign separately for bright and dark/gray tiles, **and** we must use separate bitmasks for those runs so that the targets are treated correctly.

2.  If we want to run all tiles together and use the default bitmasks, then the upstream code needs to split these targets into 2 separate target IDs with different DESI_TARGET and obsconditions values.

**Comment by sbailey** [comment]
Documenting discussion with @geordie666 @tskisner and @sbailey : move the logic about what is science / std / sky / safe / exclude for each program (dark, gray, bright, ...) into desitarget along with the bit definitions, rather than having fiberassign try to track this in parallel.  Include a unit test in desitarget that ensures that every defined bit is included in some category (e.g. to make sure that when we add a bit we include it in some category).

**Comment by tskisner** [comment]
I believe that all this discussion is actually implemented, at least in fiberassign:

- Fiberassign uses default bitmasks for all types from desitarget.  These can be overridden.  All of the logic for determining whether a target is a standard, sky, etc is outsourced to desitarget or to user-provided bitmasks.  

- Duplicate target IDs in multiple input files trigger an exception in fiberassign.   

- If a target is both a science and a standard in a single program, then:

  1.  It will first be assigned as a science and its obs remaining will be decremented.

  2.  When assigning standards, this dual target will count towards the standards budget.

  3.  When bumping science for standards / sky, dual targets are explicitly excluded from
       consideration.

  4.  After a dual target has NUMOBS_MORE == 0, it will no longer be assigned as a science
      target.  However, it will still be considered for assignment as a standard.

Closing this now, but feel free to reopen if there is a lingering problem with the logic above.
