### ISSUE TITLE
sky monitor assignment when no SKY are available

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#190]
From #187:

The sky monitor fibers normally would be assigned to SKY targets.  There will be cases where there are no good SKY targets, in which case they should fall back to using a BAD_SKY location (but not a science target since ).  If we ever have cases without either SKY or BAD_SKY, track those down.

FIBERSTATUS bookkeeping is already included in FASSIGN for sky monitor positioners too, e.g. if one of them breaks, but we could also add a bit for BAD_SKY for convenience.

**Comment by Srheft** [comment]
@sbailey:
Fibers 5010 and 5011 in tile 300005 in [this](http://www.astro.utah.edu/~u6022465/cmx/all_STDtest_SV0bright/) assignment are left unassigned although there seems to be BAD_SKY positions available for them. 

![image](https://user-images.githubusercontent.com/32471902/53999750-e4bee800-4101-11e9-9443-aef8f14d81f3.png)


@tskisner @kdawson1000:
On the last comment in #187:

> We are going to need a solution to the way that the sky monitor fibers are documented

qa.json files already provide a useful easy-access assignment summary but there may be a way to make it useful for ETC folks ([example](http://www.astro.utah.edu/~u6022465/cmx/all_STDtest_SV0bright/qa.json) from the current master for tile 300005). 

In Tile 300005 all the POS fibers are assigned so the key "unassigned" showes empty and we seem to be "good to go" if we don't look at the plots [in cases of 1000s of tiles, plotting or looking at all of them may not even happen]. 

option 1: adding the **unassigned ETC** fibers to list of "unassigned" fibers.
option 2: dividing "unassigned" key into "unassigned POS" and "unassigned ETC" 

Is this a sensible proposal? and if yes, does any other option come to mind?

**Comment by tskisner** [comment]
The current code only attempts to assign sky targets to the ETC fibers:

https://github.com/desihub/fiberassign/blob/master/py/fiberassign/scripts/assign.py#L326

That is why the ETC fibers are not assigned (there are no sky targets there, only bad sky targets which are of TARGET_TYPE_SAFE).

This was my original question- do we want to allow the ETC fibers to be assigned to "bad sky"?  If so, it is a one line change.

I have no preference for how we want to track ETC fibers in the QA.

**Comment by Srheft** [comment]
Correct. Just wanted to document an example for cases where there is simply no sky available and so we juat have to go for BAD_SKY.

**Comment by dkirkby** [comment]
> We are going to need a solution to the way that the sky monitor fibers are documented

Can someone expand on this comment? (I already read #187 but still confused).  For the downstream SkyCam analysis, I think the only think I need to know from FA is if any of the 20 sky fibers are known to not be on blank sky.

**Comment by tskisner** [comment]
Hi @dkirkby , Ok, in that case I think that @sbailey 's proposal at the beginning of this thread is the correct behavior:

1.  Try to assign sky to ETC fibers.

2.  If any are unassigned, assign them to BAD_SKY and flag them via one bit of the FIBERSTATUS field.

Currently both the normal positioners and the ETC positioners have a FIBERSTATUS column in their HDUs, and 2 bits are used to indicate stuck and broken fibers.  We could use the next bit for "bad sky".

Actually, even in the case of normal positioners maybe it is useful to flag them with this FIBERSTATUS bit?

**Comment by kdawson1000** [comment]
Hi Ted, David,
First, my original comment was quite ambiguous, I see in re-reading it.  Those comments from Stephen and Sarah do a better job of conveying the issue.  

I agree with Ted's list, but I think we need to add something along the lines of Sarah's comment:
1.  Assign sky targets to ETC fibers
2.  If any are unassigned, assign them to BAD_SKY and flag them via one bit of the FIBERSTATUS field.  (make sure that the people running the exposure time calculator are aware of the flagging system).
3.  In the case that there are ETC fibers still left unassigned, then trigger a high-level flag that indicates a critical failure in the fiber assignment of this tile.

This last point needs to be done, but I am not yet familiar with the final QA of fiber assignment to understand whether the tools are in place to do so.  I was planning ask Sarah for details on QA in the afternoon.

**Comment by dkirkby** [comment]
I suspect your 3rd case will happen often enough that we don't want to consider it a "critical failure".  The SkyCam analysis shouldn't break even if a few fibers are on bright stars.

**Comment by kdawson1000** [comment]
I agree that the 3rd case will likely happen more than we want.  But we are currently requiring that every fiber in the spectrographs has a target assigned to it, which I think is appropriate.  I think we should require the same of the ETC fibers, so that we always know where and why the fiber got the target that it got.

**Comment by tskisner** [comment]
@kdawson1000 , you said, "But we are currently requiring that every fiber in the spectrographs has a target assigned to it...", but the ETC fibers will always be assigned (they can be always be assigned to bad_sky with the one-line change I mentioned above).

**Comment by kdawson1000** [comment]
Yes, in principle you are right.  In practice, there will still be cases where some unexpected collisions or other unexpected program leave a few ETC fiber unassigned.  I am beginning to see that as inevitable as we plan to tile the entire DESI footprint.

Hopefully I am proven wrong - but we should trigger a tile-level flag to identify tiles that have unassigned science fibers or ETC fibers to alert us if those cases do arise.

**Comment by sbailey** [comment]
I believe the core issue here was addressed in PR #191, which is now merged.  i.e. if sky monitor fibers can't reach a SKY target, they are assigned to a BAD_SKY location instead and their FIBERSTATUS is set to non-zero as a warning to not use this fiber for ETC sky background estimation.  The same infrastructure applies to normal positioners too, and also to sky monitor positioners if they become stuck or have broken fibers.

@Srheft and @kdawson1000 do you agree that this issue can be closed?  Or do you have other concerns (possibly for other tickets)?

**Comment by Srheft** [comment]
@sbailey, @tskisner:

Yes, I do confirm that the ETC fibers are now assigned to BAD_SKY if no good SKY is available:

![image](https://user-images.githubusercontent.com/32471902/54325851-e25d0200-45c9-11e9-8213-4b37a6baf05f.png)



Thank you; this ticket can be closed.
