### ISSUE TITLE
fiberassign should require OBSCONDITIONS in input

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#195]
Documenting a workshop conversation in a ticket to give others who aren't here a chance to comment before we implement:

Make fiberassign require OBSCONDITIONS as an input column, instead of defaulting to allowing any conditions if the column is missing.  This means that we would also need to set OBSCONDITIONS in the sky catalogs.

i.e. in fiberassign.targets around line 188, change
```python
    if "OBSCONDITIONS" in tgdata.dtype.fields:
        d_obscond[:] = tgdata["OBSCONDITIONS"][:]
    else:
        # Set obs conditions mask to be all bits
        d_obscond[:] = np.invert(np.zeros(nrows, dtype=np.int32))
```
to
```
    d_obscond[:] = tgdata["OBSCONDITIONS"][:]
```

The motivation is to avoid a situation where someone makes a custom input that doesn't include OBSCONDITIONS and doesn't realize that fiberassign will then assign dark targets to bright tiles without any warning.

**Comment by tskisner** [comment]
fixed by bf9704ea83e0f4d5edbf956356e006aacf203ce0
