### ISSUE TITLE
fiberassign on --survey sv1 select_mock_targets. 

### ISSUE THREAD

**Issue by michaelJwilson** [desihub/fiberassign#201]
On the master branch, running:

```
select_mock_targets 
--output_dir /global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets 
--config /global/homes/m/mjwilson/desi/survey-validation/svdc-summer2018/mock-targets.yaml 
--seed 123 
--nside 64 
--survey sv1 
--healpixels 25912 25913 25914 25915 25916 25917 25918 25919 25962 26000 26001 26002 26003 26004 26005 26006 26007 26012 26013 26048 26050

join_mock_targets 
--mockdir /global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets

fiberassign  
--mtl /global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets/mtl.fits 
--stdstar /global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets/standards-dark.fits 
--sky /global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets/sky.fits 
--surveytiles /global/cscratch1/sd/mjwilson/svdc-summer2018/master/tiles/bgs-gama-tiles-kdawson-100000.txt 
--footprint /global/cscratch1/sd/mjwilson/svdc-summer2018/master/tiles/bgs-gama-tiles-100000.fits 
--fibstatusfile /global/homes/m/mjwilson/desi/survey-validation/svdc-summer2018/fiberstatus.ecsv 
--outdir /global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-fiberassign
```

Results in 

```
No field of name DESI_TARGET from fiberassign/targets.py
```

Given the .mtl has columns:

![image](https://user-images.githubusercontent.com/6034066/57813503-30ef5f80-7725-11e9-936a-6fd2e3ea190f.png)

parse_assign() of fiberassign/scripts/assign.py takes a bunch of relevant looking arguments, e.g. --mask_column that bin/fiberassign does not?  Maybe I'm calling it incorrectly.

**Comment by forero** [comment]
I tried directly `fba_run` (`fiberassign` is wrapper meant to be backwards compatible but it seems that it's hard to make it work with SV data) using `--mask_column SV1_DESI_TARGET` as follows:

```
fba_run 
--targets /global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets/mtl.fits 
/global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets/standards-dark.fits
/global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets/sky.fits 
--tiles /global/cscratch1/sd/mjwilson/svdc-summer2018/master/tiles/bgs-gama-tiles-kdawson-100000.txt 
--footprint /global/cscratch1/sd/mjwilson/svdc-summer2018/master/tiles/bgs-gama-tiles-100000.fits
--mask_column SV1_DESI_TARGET --dir ./
```
and got a different error `RuntimeError:   Duplicate target IDs are not permitted.`

Here is the full output:

```
INFO: Reading fiber positions from /global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desimodel/master/data/focalplane/fiberpos-all.fits
INFO: Target file /global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets/mtl.fits has 45491 rows.  Reading in chunks of 1000000
INFO: Read target file /global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets/mtl.fits:  0.32 seconds (1 calls)
INFO: Target file /global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets/standards-dark.fits has 4667 rows.  Reading in chunks of 1000000
ERROR: Target ID 288230484834518319 already exists with properties: (212.335,-3.03249) (0,0.607431) 0, 7, 2
ERROR:   New target properties: (212.335,-3.03249) (0,0.607431) 0, 3
ERROR:   Duplicate target IDs are not permitted.
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/bin/fba_run", line 20, in <module>
    main()
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/bin/fba_run", line 15, in main
    run_assign_full(args)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/py/fiberassign/scripts/assign.py", line 300, in run_assign_full
    hw, tiles, tgs = run_assign_init(args)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/py/fiberassign/scripts/assign.py", line 266, in run_assign_init
    excludemask=args.excludemask)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/py/fiberassign/targets.py", line 642, in load_target_file
    excludemask=excludemask)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/py/fiberassign/targets.py", line 571, in load_target_table
    stdmask, skymask, safemask, excludemask)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/py/fiberassign/targets.py", line 414, in append_target_table
    d_subprior, d_obscond, d_type)
RuntimeError:   Duplicate target IDs are not permitted.
```

**Comment by sbailey** [comment]
@forero the duplicate target ID problem is issue #198 .  If your stdstar list is a subset of the mtl list, you could just drop it when using fba_run.

@michaelJwilson are you also using desitarget master?  Or just fiberassign master with a tagged desitarget?  It looks like the autodetection isn't working for whether your MTL is SV1 vs. main survey, though`desitarget.targets.main_cmx_or_sv(targets)[2]` using desitarget master correctly reports 'sv1'.

Using fiberassign master I haven't been able to reproduce your problem because of the same duplicate target ID from #198.  Did you hack your copy of the code to work around that?  i.e. I don't know whether desitarget is correctly identifying SV1 and fiberassign is failing to do the right thing with that info, or whether you have an older version of desitarget that isn't identifying sv1 correctly or something else.

**Comment by forero** [comment]
@sbailey Thanks. Indeed, dropping the `standards-dark.fits` file works.

**Comment by moustakas** [comment]
@rstaten reported this same (or similar) issue to me over email but I hadn't had a chance to dig in.  @rstaten can you check against your usage of `select_mock_targets` and `fiberassign` and report here?

**Comment by rstaten** [comment]
@moustakas I used the instructions given in quicksurvey_example and am using master version of both desitarget and fiberassign. As @sbailey mentioned, the duplicate ID problem that I see is noted in #198. The commands given are:

select_mock_targets --no-spectra --nproc 4 --nside 16 --seed 10 \
    -c $SCRATCH/quicksurvey_example/targets/no_spectra/dark/input.yaml \
    --output_dir $SCRATCH/quicksurvey_example/targets/no_spectra/dark \
    --tiles $SCRATCH/quicksurvey_example/survey/subset_tiles_dark.fits

join_mock_targets --mockdir $SCRATCH/quicksurvey_example/targets/no_spectra/dark

fiberassign --mtl $SCRATCH/quicksurvey_example/targets/no_spectra/dark/mtl.fits \
    --stdstar $SCRATCH/quicksurvey_example/targets/no_spectra/dark/std.fits \
    --sky $SCRATCH/quicksurvey_example/targets/no_spectra/dark/sky.fits

**Comment by michaelJwilson** [comment]
Confirming that Jaime's call works for me.  I'm (attempting to work on master for everything). 
I.e. 

```
source /project/projectdirs/desi/software/desi_environment.sh master

fba_run 
--targets /global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets/mtl.fits /global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets/sky.fits 
--tiles /global/cscratch1/sd/mjwilson/svdc-summer2018/master/tiles/bgs-gama-tiles-kdawson-100000.txt 
--footprint /global/cscratch1/sd/mjwilson/svdc-summer2018/master/tiles/bgs-gama-tiles-100000.fits 
--mask_column SV1_DESI_TARGET 
--dir ./
```

![image](https://user-images.githubusercontent.com/6034066/57863290-a94e3300-77ae-11e9-8033-8fa34dc8aa02.png)

Incidentally, I did try: 

```
read_targets_in_hp('/global/cscratch1/sd/mjwilson/svdc-summer2018/targets/', nside=64, pixlist=[25912], header=False)
```

to look at the output of ```desitarget.targets.main_cmx_or_sv``` as suggested by @sbailey.  There seems to be a difference in the expected header, between FILENSIDE (desitarget.io) and HPXNISDE (desitarget/mock).

**Comment by geordie666** [comment]
Some context: In the headers of desitarget output files:

- `HPXNSIDE` refers to the HEALPixel `nside` at which the `HPXPIXEL` column is stored. This should be propagated downstream.
- `FILENSID` refers to the pixelization that was used when target-production was parallelized across pixels. This is utilized in wrapper routines such as [read_targets_in_box](https://github.com/desihub/desitarget/blob/master/py/desitarget/io.py#L1326) and [read_targets_in_cap](https://github.com/desihub/desitarget/blob/master/py/desitarget/io.py#L1326). `FILENSID` is specific to `desitarget` and probably doesn't need to be propagated downstream, particularly if fiberassign is going to be run one-tile-at-a-time.

`HPXNSIDE` should (will) certainly always appear in the `desitarget` output file headers, though.

**Comment by geordie666** [comment]
Further `read_targets_in_hp` is designed to work with files that have been written by `desitarget.io` itself. Those files must have a nomenclature like files in the following directory:

 /project/projectdirs/desi/target/catalogs/dr7.1/0.29.0/sv/

and must include the `FILENSID` header entry. I don't think the mocks use the full `desitarget.io` formalism when reading and writing data, so `read_targets_in_hp` won't work with mock files.

**Comment by moustakas** [comment]
> and must include the FILENSID header entry. I don't think the mocks use the full desitarget.io formalism when reading and writing data, so read_targets_in_hp won't work with mock files.

They don't, but do we want to add this feature into the mock targets I/O?

**Comment by geordie666** [comment]
If that's desired, I don't think it would be hard. All we'd need is the following three fixes:

- Change the files to look like: `sv1-blat-hp-X.fits`, where X is a HEALPixel integer.
- Add `FILENSID` to the header entry, setting it to the `nside` for X (or use `desitarget.io.write_targets` passing `nsidefile=nside`.
- Group the output files in a single directory rather than across different directories (this might be the dealbreaker).

On the third desideratum: I'd assumed that the target files would have their own, single output directory and then each tile would be passed to fiberassign using something like `desitarget.io.read_targets_in_cap`.

**Comment by geordie666** [comment]
Note, though, that with the current directory structure that @michaelJwilson is using, e.g.:

`/global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets/259/25912/targets-64-25912.fits`

There's no particular reason to use the `read_targets_in_hp` utility. 

`read_targets_in_hp` is useful when you have a single file, or a directory that contains multiple files, that span multiple HEALPixels and you want to read targets in one (or a subset) of those HEALPixels. 

If you're working with single files that are already split by HEALPixel, then the only reason for using `read_targets_in_hp` would be to read in a single file and only pull out a subset of targets at a different `nside` to the one at which the file was written.

For example, if the mock files contained the `FILENSID` header entry (and it was set to 64) then the following should work:
```
blat = read_targets_in_hp("/global/cscratch1/sd/mjwilson/svdc-summer2018/master/sv-targets/259/25912/targets-64-25912.fits", nside=64, pixlist=[25912])
```
but it would be exactly equivalent to reading in the entire file!

**Comment by sbailey** [comment]
Let’s keep the current file structure where the mocks are grouped the same as the spectro pipeline output spectra and redshifts, ie one file per healpix grouped in subdirs by pix//100

**Comment by michaelJwilson** [comment]
Closing this out, given that #198 seems sufficient.
