### ISSUE TITLE
FIBERID or LOCATION in fba_run_qa

### ISSUE THREAD

**Issue by Srheft** [desihub/fiberassign#210]
@sbailey @tskisner:

[device_locations('POS') ](https://github.com/desihub/fiberassign/blob/fc1c7f8e39af589b61abfe70e8f3b2d7885c9e89/py/fiberassign/qa.py#L78) goes 0 to 9526 making the list of unassigned fibers in qa.json to report invalid FIBERIDs. This does not affect fba_run. Produced Fits Tables have been unaffected.

An example is shown [here](http://www.astro.utah.edu/~u6022465/cmx/ALL_SKY/dr8/allSKY_ci_tiles/sub_pages/tile-58180.html).

**Comment by sbailey** [comment]
PR #204 switched to labeling the positioners by their LOCATION = 1000*PETAL_LOC + DEVICE_LOC instead of FIBERID.  Does qa.json still call these "FIBERID" or is it just a list of numbers that used to mean FIBERID and now means LOCATION?

**Comment by Srheft** [comment]
Ok i was not aware of that change; I shall be pinged ;)

lf i were to convert the content of unassigned list to xy and then to
ra,dec, then this change makes it impossible to do that(unless I reverse
your labeling and translate them to valid POS fiber ids). in the coverage
test for GFA and Sky catalog, it is useful for targeting folks to know
where they lack targets and tile center coordinates are not local enough.
Your change is useful in some regards though.

**Comment by sbailey** [comment]
It looks like unassigned fibers appear in the FIBERASSIGN table with negative TARGETIDs and FIBERSTATUS=1, but meaningful TARGET_RA, TARGET_DEC.  Is that sufficient for your case of wanting to know the RA, DEC of unassigned fibers?  Or am I misunderstanding those outputs or what you need?

**Comment by Srheft** [comment]
we want to keep tilepicker light
 If it gets all the useful info from qa.json and independent from parsing
through fits tables then that's great. All coloring(green-good tile, red-
bad tile) and assignment and gfa info are coming from qa.jsin that is very
quick and convenient. Now that I know your labeling convention, I get the
radec from converted fibids.

**Comment by Srheft** [comment]
Hi 2sbaile

I tried to add
