### ISSUE TITLE
Uniform sky assignment per cassette not petal

### ISSUE THREAD

**Issue by tskisner** [desihub/fiberassign#214]
Currently we attempt to have more uniform sky assignment by tallying the number of sky fibers assigned per petal.  For cases where a petal is on the edge of the footprint, this could lead to a petal's sky fibers all being assigned to one part of the petal.

We should add support for tracking the sky totals per cassette rather than per petal.  A cassette consists of two slitblocks and these are spatially grouped near each other on the focalplane.  This consists of a slight change to the API of `Assignment::assign_unused()` and `Assignment::assign_force()` and the python bindings and higher-level code that calls these.

Note that this is loosely related to questions asked in #151, however that issue was focused on the algorithm used, not the area over which to do the balancing.

**Comment by tskisner** [comment]
Revisiting as of Spring 2020.  Implementing this change to specify a maximum number of standards, sky, etc per cassette instead of petal is a tedious change (mostly changing strings and calling a function to query the cassette for given location rather than the petal).  However, there are no real technical or algorithmic changes involved.  Just a question of whether we need to do this to achieve successful sky subtraction.

**Comment by tskisner** [comment]
Since this change is needed for #324, I wanted to clarify whether we want to enforce a certain number of sky per cassette or per slitblock? @djschlegel do you have any thoughts / preference?

**Comment by julienguy** [comment]
If this question is still open, there is a preference of 1 per slit block because
 1) we do see correlated sky residuals in the frames with a correlation length close to 25 fibers (size of a block).
 2) there are genuine discontinuity of wavelength solution and PSF shape between slit blocks because the glass blocks are not perfectly aligned along the slit.

**Comment by djschlegel** [comment]
The simplest implementation would be to demand 2 skies per slit block, giving the number number of 40 skies per spectrograph.  I'd suggest we start with that implementation, and then see how well it works when running fiberassign on the real full-sky catalogs.

**Comment by tskisner** [comment]
In terms of implementation there is no difference.  We are switching our counters from being indexed by "petal" to being indexed by "something else".  Currently when assigning a location, we lookup the petal for that location and increment the counter for the petal.  Instead we will look up the slitblock or cassette for that location and increment the counter indexed on that.

We have the slitblock for each positioner already internally in fiberassign.  Is the cassette "index" just `int(slitblock / 2)`?

**Comment by djschlegel** [comment]
I suspect a cassette can be non-adjacent slitblocks; I don't recall.  Regardless, let's go with Julien's suggestion of using the slitblock.

**Comment by deisenstein** [comment]
Since we are hopefully going to have some skies from non-moving
positioners, how many such positioners do we need in a slitblock before we
would decide to have 1 positioned sky instead of 2?  To have 0?

A concrete proposal would be 2 non-moving fibers to offset one moving
fiber.  And then require 2 moving per block (so 2 non+1 move, or 4 non,
would suffice).

**Comment by djschlegel** [comment]
Daniel-- We'll be pre-determining which nonfunctional positioners are good skies.  So it's better than that, and more like 75% will be good skies.

**Comment by djschlegel** [comment]
If we require 2 skies per slitblock (and only count 2 per slitblock), and if 75% are on good sky locations, that will typically count for 181 skies.  Different schemes don't actually give us many more -- if we counted up to 4 per slitblock, that's only 208 skies typically.
<img width="573" alt="Screen Shot 2021-04-21 at 3 11 35 PM" src="https://user-images.githubusercontent.com/7918018/115627696-4cb9f380-a2b4-11eb-8417-d2348dc5a11d.png">

**Comment by deisenstein** [comment]
Great.  That seems reasonable to me.  So we can expect about 220 working
fibers (5%) to go to sky.

**Comment by tskisner** [comment]
Ok, it seems like we have converged to using a slitblock rather than a cassette as the unit to balance over.  The actual number per unit (slitblock) is a high-level parameter which is user-specified by the calling code or commandline.

**Comment by dstndstn** [comment]
Done in #338
