### ISSUE TITLE
Tile selection bug

### ISSUE THREAD

**Issue by tskisner** [desihub/fiberassign#218]
There is small bug in this line:

https://github.com/desihub/fiberassign/blob/master/py/fiberassign/tiles.py#L40

Where the result of "np.where" is a tuple and we should be using the first element of that.  In addition to that trivial fix though we should also add tile selection to the unit tests and verify that it works as expected.

**Comment by sbailey** [comment]
When that tuple is used for slicing an array, it still works, so I don't think this is a bug that changes behavior.  e.g.
```
In [1]: x = np.arange(10)                                                       

In [2]: ii = np.where(x>5)                                                      

In [3]: jj = np.where(x>5)[0]                                                   

In [4]: x[ii]                                                                   
Out[4]: array([6, 7, 8, 9])

In [5]: x[jj]                                                                   
Out[5]: array([6, 7, 8, 9])
```

we could still add the `where(...)[0]` for clarity.

+1 for unit tests.

**Comment by tskisner** [comment]
This was fixed long ago.
