### ISSUE TITLE
fba_merge_results corrupting previously merged output

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#221]
A usage gotcha:

Imagine running fba_run + fba_merge_results for a set of tiles (e.g. dark tiles).  Then run them again for a different MTL with a different set of tiles (e.g. bright tiles), but output to the same directory.  In this case the second fba_merge_results will merge all the fba_run output that it can find (fiberassign_*.fits), including the ones from the first run.  But the previously merged results were from the dark MTL and now it is trying to merge them with a bright MTL and it can't find a bunch of targets.  It silently rewrites those previously merged files and corrupts them with DESI_TARGET=0.

Options:
  * don't remerge something if the output already exists
  * provide a --tiles option to fba_merge_results just like fba_run and only process those tiles
  * something else

In the meantime the workaround is to always run batches of fiberassign in a blank output directory and then copy the results into a final location when done.

**Comment by Srheft** [comment]
@sbailey  
could the solution be one of these:
 to add --overwrite for **fba_merge_results** similar to the one in **fba_run**  and have it not be used unless the user really does want to rewrite the previously merged results and if the --overwrite is not used, then the merged outputs would have tile-XXXXX.fits-1... N 
OR 
right before writing the merged results into a tile-XXXXX.fits file, have fiberassihn to check the --out directory for tile-XXXXX.fits files; if it exists, write the merged results in tile-XXXXX.fits-1

**Comment by tskisner** [comment]
The merging function now explicitly removes any output file before writing the newly merged one:

https://github.com/desihub/fiberassign/blob/master/py/fiberassign/assign.py#L1142

Is this sufficient?

**Comment by tskisner** [comment]
Closing this now since the point of this issue (data corruption) never happens with the current code (since outputs are explicitly removed before writing).  We can open a new issue if some other behavior is desired.
