### ISSUE TITLE
Don't propagate 2D target columns into FIBERASSIGN HDU

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#237]
ICS uses Pandas dataframes to parse fiberassign tables, but Pandas doesn't support 2D columns.  When merging the target catalog into the FIBERASSIGN table, exclude 2D columns.

Example problem at KPNO:
```python
import fitsio
t = fitsio.read('/data/tiles/ALL_tiles/v1/fiberassign-059958.fits', 'FIBERASSIGN')
for name in t.dtype.names:
    if len(t[name].shape) > 1:
        print(name, t[name].shape)

...
DCHISQ (5000, 5)
```

It is not yet known whether we have to exclude these from both the FIBERASSIGN and TARGETS HDU, or whether it is sufficient to exclude them from just the FIBERASSIGN HDU (hopefully).

**Comment by moustakas** [comment]
Better yet would be to assess whether we need `DCHISQ` in the sweeps in the first place. https://github.com/desihub/desitarget/issues/197
