### ISSUE TITLE
problem running example for fiberassign

### ISSUE THREAD

**Issue by rncahn** [desihub/fiberassign#239]
rncahn@nid00191:/global/cscratch1/sd/rncahn> time fba_run \
>     --targets ${targetdir}/mtl.fits \
>     ${targetdir}/standards-bright.fits \
>     ${targetdir}/standards-dark.fits \
>     ${targetdir}/sky.fits \
>     --dir out_ref_18.11 | tee log_ref_18.11
DEBUG:io.py:292:load_focalplane: Loading focalplanes from /global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desimodel/master/data/focalplane
INFO: Loaded focalplane for time stamp 2019-11-26 21:54:37.675855
DEBUG:   focalplane table keeping 5020 rows for POS and ETC devices
INFO: Focalplane has 0 fibers that are stuck / broken
DEBUG:io.py:204:load_tiles: Loading tiles from /global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desimodel/master/data/footprint/desi-tiles.fits
INFO: Target file /project/projectdirs/desi/datachallenge/reference_runs/18.11/targets/mtl.fits has 224266 rows.  Reading in chunks of 1000000
DEBUG: Target file /project/projectdirs/desi/datachallenge/reference_runs/18.11/targets/mtl.fits read rows 0 - 224265
DEBUG: Target table using survey 'main', column DESI_TARGET:
DEBUG:   sciencemask LRG|ELG|QSO|BGS_ANY|MWS_ANY|SCND_ANY
DEBUG:   stdmask     STD_FAINT|STD_WD|STD_BRIGHT
DEBUG:   skymask     SKY
DEBUG:   safemask    BAD_SKY
DEBUG:   excludemask BRIGHT_OBJECT|IN_BRIGHT_OBJECT
DEBUG: Survey main target ID 288230398217946395 type not identified- SKIPPING
DEBUG: Survey main target ID 288230398217946402 type not identified- SKIPPING
DEBUG: Survey main target ID 288230398217946410 type not identified- SKIPPING
DEBUG: Survey main target ID 288230398217946417 type not identified- SKIPPING
DEBUG: Survey main target ID 288230398217946425 type not identified- SKIPPING
DEBUG: Survey main target ID 288230398217946431 type not identified- SKIPPING

[skipped some lines here]

DEBUG: Survey main target ID 288230399866309759 type not identified- SKIPPING
INFO: Read target file /project/projectdirs/desi/datachallenge/reference_runs/18.11/targets/mtl.fits:  2.51 seconds (1 calls)
INFO: Target file /project/projectdirs/desi/datachallenge/reference_runs/18.11/targets/standards-bright.fits has 3100 rows.  Reading in chunks of 1000000
DEBUG: Target file /project/projectdirs/desi/datachallenge/reference_runs/18.11/targets/standards-bright.fits read rows 0 - 3099
DEBUG: Target table using survey 'main', column DESI_TARGET:
DEBUG:   sciencemask LRG|ELG|QSO|BGS_ANY|MWS_ANY|SCND_ANY
DEBUG:   stdmask     STD_FAINT|STD_WD|STD_BRIGHT
DEBUG:   skymask     SKY
DEBUG:   safemask    BAD_SKY
DEBUG:   excludemask BRIGHT_OBJECT|IN_BRIGHT_OBJECT
ERROR: Target ID 288230398217949145 already exists with properties: (152.785,28.3289) (0,0.248582) 0, 4, 2
ERROR:   New target properties: (152.785,28.3289) (-1,0.248582) 0, 4
ERROR:   Duplicate target IDs are not permitted.

**Comment by sbailey** [comment]
Thanks for trying this out and reporting that the [example documentation](https://github.com/desihub/fiberassign/blob/master/doc/examples.rst) is out of date.

Please try with a more recent reference run (e.g. /project/projectdirs/desi/datachallenge/reference_runs/19.10/targets/) which now has standards includes as part of the targets and thus shouldn't have duplicated targetids.  If that works, please update the example docs (https://github.com/desihub/fiberassign/blob/master/doc/examples.rst) with the appropriate recipe, or otherwise report back what doesn't work.

**Comment by rncahn** [comment]
Doesn't quite work.  Compare 18.11 with 19.10:
rncahn@cori09:/project/projectdirs/desi/datachallenge/reference_runs/18.11/targets> lsalt
total 244358
dr-xr-s---+  2 sjbailey   131072 Nov  8  2018 qa
dr-xr-s---+  6 sjbailey     4096 Nov  8  2018 .
dr-xr-s---+  6 sjbailey     4096 Nov  8  2018 ..
dr-xr-s---+ 10 sjbailey     4096 Nov  8  2018 56
dr-xr-s---+ 17 sjbailey     4096 Nov  8  2018 53
dr-xr-s---+ 25 sjbailey     4096 Nov  8  2018 52
-r--r-----   1 sjbailey 93539520 Nov  8  2018 mtl.fits
-r--r-----   1 sjbailey 39343680 Nov  8  2018 truth.fits
-r--r-----   1 sjbailey 93556800 Nov  8  2018 targets.fits
-r--r-----   1 sjbailey  1356480 Nov  8  2018 standards-bright.fits
-r--r-----   1 sjbailey  1347840 Nov  8  2018 standards-dark.fits
-r--r-----   1 sjbailey 20059200 Nov  8  2018 sky.fits
-r--r-----   1 sjbailey    29007 Nov  8  2018 select_mock_targets.log
-r--r-----   1 sjbailey     1650 Nov  8  2018 select-mock-targets.yaml
-r--r-----   1 sjbailey     8640 Nov  8  2018 test-tiles.fits

rncahn@cori09:/project/projectdirs/desi/datachallenge/reference_runs/19.10/targets> lsalt
total 360453
dr-xr-s---+  2 sjbailey   131072 Oct 31 15:59 qa
dr-xr-s---+  6 sjbailey   131072 Oct 31 15:59 .
dr-xr-s---+  6 sjbailey     4096 Oct 31 15:59 ..
dr-xr-s---+ 25 sjbailey     4096 Oct 31 15:59 52
dr-xr-s---+ 10 sjbailey     4096 Oct 31 15:59 56
dr-xr-s---+ 17 sjbailey     4096 Oct 31 15:59 53
-r--r-----   1 sjbailey 89176320 Oct 30 15:07 mtl-dark.fits
-r--r-----   1 sjbailey 35781120 Oct 30 15:07 truth-dark.fits
-r--r-----   1 sjbailey 86967360 Oct 30 15:07 targets-dark.fits
-r--r-----   1 sjbailey 57646080 Oct 30 15:07 mtl-bright.fits
-r--r-----   1 sjbailey 18463680 Oct 30 15:07 truth-bright.fits
-r--r-----   1 sjbailey 56223360 Oct 30 15:07 targets-bright.fits
-r--r-----   1 sjbailey 23970240 Oct 30 15:07 sky.fits
-r--r-----   1 sjbailey    30239 Oct 30 15:02 select_mock_targets.log
-r--r-----   1 sjbailey     2569 Oct 30 14:32 select-mock-targets.yaml


Questions:  
19.10 doesn't have standards.  I can check to see that 18.11 and 19.10 use the same patch.  if so, I could use the standards from 18.11 with the targets from 19.10.  I also need to use the actual file names in 19.10, i.e. mtl-dark.fits, mtt-bright.fits in place of mtl.fits, etc.

**Comment by rncahn** [comment]
There is a target that appears both in mtl-dark and mtl-bright in 19.10


from mtl-dark
FITS_rec([(9999, 488659, '1526p285',    0, 'DEV', 152.54911804, 28.58329391, 1.e+08, 1.e+08, [  0., 100., 200., 300., 400.],   3.8110943 ,  10.583877 ,  21.462357 , 2.8384859e+01, 2.2990866e+01, 0., 0., 1438.5999, 329.56418, 62.79716, 0.75525916, 0.299417  , 0., 0., 0.9444018 , 0.96219975, 0.97850275, 0.9967305 , 0.99799085, 0.99957114, 0.99983805, 2, 2, 2, 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0, 0, 52.480747, 7.7268057, 1.8706821, 57.543995, 13.182568, 2.5118864, 1., 0., 0.88958037, 10310.31 ,  0.14493127, 1.5047821e+13, 0.25267327,  9374.479, 0.        ,     0.     , 0., 0., 0., 0.,  1.089443  ,   3.1649563 , 6.7515621e+00,  1.089443  ,   3.1649563 , 6.7515621e+00, '',                 -1,  0.      , 0., 0., 0., 0., 0., 0., 0.,  0, 0.,  0,  0.        ,   1.     ,   0.       ,   1.      ,  0.       , 1.        , 0, 0.0193242 , 'S', 288230398217945088, 1152921504606846976, 1,   0, 0.35681036, 7, 2000, 1, 5261, 1, 2000),


from mtl-bright
FITS_rec([(9999, 488659, '1526p285',    0, 'DEV', 152.54911804, 28.58329391, 1.e+08, 1.e+08, [  0., 100., 200., 300., 400.],   3.8110943,  10.583877 ,  21.462357,   28.38486,   22.990866, 0., 0., 1438.5999, 329.56418, 62.79716, 0.75525916, 0.299417  , 0., 0., 0.9444018 , 0.96219975, 0.97850275, 0.9967305 , 0.99799085, 0.99957114, 0.99983805, 2, 2, 2, 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0, 0, 52.480747, 7.7268057, 1.8706821, 57.543995, 13.182568, 2.5118864, 1., 0., 0.88958037, 10310.31, 0.14493127, 1.5047821e+13, 0.25267327, 9374.479, 0.        ,     0.  , 0., 0., 0., 0.,  1.089443 ,   3.1649563,   6.751562,  1.089443 ,   3.1649563,   6.751562, '',                 -1,  0.      , 0., 0., 0., 0., 0., 0., 0.,  0, 0.,  0,  0.        ,   1.      ,   0.       ,   1.      ,  0.       , 1.        , 0, 0.0193242 , 'S', 288230398217945088, 1152921504606846976, 1,   0, 0.35681036, 7, 2000,  1, 5261, 1, 2000),

**Comment by tskisner** [comment]
Coming back to this.  The error condition when a target shows up twice for a single fiberassign run is intentional.  It was too challenging to "guess" whether the input targets were intended to be the same target or whether it was a problem with the MTL generation.  So fiberassign just raises an exception.

**Comment by forero** [comment]
I checked that the current fiberassign version works well with the example document here https://github.com/desihub/fiberassign/blob/master/doc/examples.rst

As @tskisner pointed out the error appeared because mtl-dark and mtl-bright were passed at the same time to fiberassign.

Closing this issue now. Feel free to open a new one if there is a problem with the fiberassign examples.
