### ISSUE TITLE
Implement ledgers for MTL

### ISSUE THREAD

**Issue by geordie666** [desihub/fiberassign#270]
If we decide to fully implement ledgers for MTL, we will need to update fiberassign to interface with the [new functionality in desitarget](https://github.com/desihub/desitarget/pull/635). The broad instructions for the overall workflow are outlined in [a comment in desitarget PR #365](https://github.com/desihub/desitarget/pull/635#issuecomment-670201875), although I'm happy to discuss further details where needed.

**Comment by tskisner** [comment]
I think this is now being done at a high level in the python / bash scripts which are calling `fiberassign.assign.run()` under the hood.  @araichoor and @geordie666 , do you think that is correct?  If so, let's close this issue.

**Comment by araichoor** [comment]
from my understanding, yes.
the fba_launch python script:
- uses desitarget tools (read_targets_in_tiles(mtl=True) and inflate_ledger()) to collect the targets with their updated mtl status (hence priority, numobs, etc)
- then calls run_assign_full to run fiber assignment.

**Comment by tskisner** [comment]
Ok, great!  Closing this now and we can reopen if needed.
