### ISSUE TITLE
Designing Commissionning fibre-assign files

### ISSUE THREAD

**Issue by araichoor** [desihub/fiberassign#275]
Principle:
Having one checked-in script (cmx-assign.py) which generates the fiberassign-{tileid}.fits files for the re-start of the commissioning, to ensure reproducibility/archiving.

Approach:
I have currently designed five commissioning flavors; it should be easy to add few other ones.

**Comment by forero** [comment]
Currently the script lives in https://github.com/desihub/fiberassign/blob/cmx_assign/bin/cmx-assign.py

**Comment by forero** [comment]
A first version of this script has been added in PR #277
