### ISSUE TITLE
problem with FLAVOR keyword in fba_cmx outputs

### ISSUE THREAD

**Issue by forero** [desihub/fiberassign#285]
Eddie writes in [desi-survey 994] (the night of 20201210):

> Klaus points out tonight that the ICS copies the headers from the primary header of the fiberassign file into the request, meaning that some keywords trigger special behavior from the ICS.  FLAVOR is one of these.

Klaus replies in [desi-survey 994]:

> Any modification of these standard keywords would work (like FAFLAVOR)
PROGRAM is also use in the exposure requests (outside of the fiberassign file)
The ICS code is set up to copy only keywords from the fiberassign header that are not already in the exposure request.
PROGRAM is typically used so if you have a PROGRAM keyword that would be ignored.
FLAVOR is different since the desi sequence uses science as default (no other flavors are supported) so the keyword can be omitted.

Proposal. Change the FLAVOR keyword to FAFLAVOR

**Comment by forero** [comment]
Solved in PR #286

**Comment by djschlegel** [comment]
That full list (I hope!) of header keywords that could conflict are in the "Primary Header" tab of this google spreadsheet: https://docs.google.com/spreadsheets/d/1Rtukds1AhloeNzRNeL6zn8IrneUVeqHf85LyJiumWe8/edit#gid=1037468760
