### ISSUE TITLE
always propagate *_TARGET columns

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#296]
Always propagate all *_TARGET columns from the input target/mtl files to the output fiberassign files, even if that column is all zeros (e.g. DESI_TARGET during SV).  Future-proof this with something like `if colname.endswith('_TARGET')` or a regex match so that it will automatically include future *_TARGET columns that we haven't even invented yet (SV2_DESI_TARGET, LIGO_TARGET, DESI2_TARGET, ...).

Credit to @djschlegel for the "future proofing" idea of propagating all *_TARGET columns instead of specifically opt-in like other columns.

**Comment by araichoor** [comment]
PR #297 addresses that issue.
