### ISSUE TITLE
track targets that got added by later optimization passes

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#3]
Fiber assignment makes several passes to optimize the assignments.  Track which targets got added at which pass and include that in the output.  This is particularly important to track which targets were assigned on the very first pass vs. later passes.

**Comment by forero** [comment]
`fiberassign` does not necessarily make several passes in the same run. Instead, different passes are handled by `quicksurvey`.

**Comment by sbailey** [comment]
Reopening and clarifying:  This ticket was referring to the swapping optimizations inside fiberassign that swap targets between tiles (see #93 for making this parameterized instead of hardcoded).  If we do allow swaps, we also want to track which targets were added due to the swaps vs. those in the original set of assignments.

**Comment by forero** [comment]
If I understand correctly `fiberassign` follows a logic of incremental optimization by swapping targets iteratively. This swapping can happen many times. Should we then track what happens at every swapping iteration?

**Comment by sbailey** [comment]
I think we only need to track the final state of whether the target was
* in the original assignments on this fiber
* in the original assignments but on a different fiber
* added due to the swapping

But we should first do the studies to determine if we really need to do swapping or not, or whether the analysis simplification of no swapping is worth the loss of fiber assignment completeness.

**Comment by sbailey** [comment]
related to #93 swapping logic flexibility

**Comment by tskisner** [comment]
I think we can close this now.  We are no longer doing "swapping", and the redistribution step (to better load balance petals) is a couple percent change.  Also, it seems like the way to account for all fiberassign effects on the final outcome is through running the assignment on simulated mock targets.
