### ISSUE TITLE
add WISE inverse variances to fiberassign files?

### ISSUE THREAD

**Issue by moustakas** [desihub/fiberassign#300]
Spinning off from #297.

Is it too late to add `FLUX_IVAR_W1` and `FLUX_IVAR_W2` to the fiberassign files? Without fluxes and inverse variances for all 5 bandpasses I have to go back to the targeting / MTL files to model the broadband photometry at the derived redrock redshift. Maybe that's not a compelling enough reason to add these two columns but I wanted to discuss it.

**Comment by araichoor** [comment]
It has been added in https://github.com/desihub/fiberassign/commit/0928a85ac78ed82e97eef2a08cc8123bbf31368b.
