### ISSUE TITLE
Development clean-ups

### ISSUE THREAD

**Issue by tskisner** [desihub/fiberassign#312]
The PR #297 broke unit tests for target QA, but was merged anyway.  Since then, unit tests have not been running at all, since travis support was deprecated but never replaced with the appropriate github actions.  There are also multiple stale branches left from closed PRs.  This issue is to track clean up of these things.

**Comment by sbailey** [comment]
Several levels of unit test protection have failed us here.
1. developers should run "python setup.py test" as part of evaluating their code before submitting pull requests (mentioning @araichoor and @forero as most active recent developers)
2. github should run tests upon PRs (the Travis -> github actions conversion hasn't happened yet)
3. the nightly updates + tests at NERSC apparently weren't running the fiberassign tests for reasons I don't understand yet: https://data.desi.lbl.gov/desi/spectro/redux/dailytest/log/cori/fiberassign.log

**Comment by tskisner** [comment]
Just FYI, the unit test breakage is a small fix, but I will fold it into the PR that converts travis to github actions.  That way the fix can be tested.  Will get to this later today.

**Comment by weaverba137** [comment]
Did fiberassign ever have coverage checks via coveralls.io set up?

**Comment by tskisner** [comment]
Re: the list in a previous comment by @sbailey , I think travis just stopped working at some point and I am switching things to github actions now in #313.  As part of that work, I noted that the test runner code was actually not exiting with a non-zero exit code if the tests failed.  This explains the behavior you saw at NERSC.  This is being fixed in that PR as well.

As for coveralls, there was no change in coverage during this issue (the test runner just stopped working in one case, and in the other the failure was simply not forcing a non-zero return status).  I imagine that coveralls would only be able to detect coverage in the python wrapper code of fiberassign, not the internal compiled code.  If someone wants to do that in the future then great, but I don't have time to do that.

**Comment by weaverba137** [comment]
@tskisner, I think we might have a slight misunderstanding here:  I don't see any evidence that fiberassign was ever sending reports to coveralls *at all*.  Did you have an independent configuration for coveralls?

I'm pretty sure I do not have that configured, even though I have coveralls configurations for many other desihub packages.

**Comment by tskisner** [comment]
No, I have never used coveralls for fiberassign.  If you are going to do that, please wait until I get #313 merged.

**Comment by weaverba137** [comment]
That's fine, I can help with the set-up on #313.

**Comment by tskisner** [comment]
This clean up is finished.
