### ISSUE TITLE
fba_launch_io.py: move away from write_targets() and write_skies()

### ISSUE THREAD

**Issue by araichoor** [desihub/fiberassign#358]
After having read the desitarget catalogs / MTL ledgers, we currently write the TILEID-{gfa,targ,scnd,too,sky}.fits files with the desitarget routines write_targets() and write_skies().

We realized that doing this involves an overwriting of the desitarget original SUBPRIORITY column (with picking a reproducible random number).

We need to not use anymore those desitarget routines when writing those files; simply use fitsio should work (maybe also check if proper information is propagated to the headers, even if those headers are not really used).

**Comment by araichoor** [comment]
@sbailey @ashleyjross @geordie666  : the currently used desitarget routines nicely adds various information in the header of those TILEID-{gfa,targ,scnd,too,sky}.fits files (see example below).
do we want the new way of writing those files to reproduce the same header keywords?

the current fix is to use a simple call to fitsio.write(), so not adding those extra header infos.
if we want to have all those extra header information, then:
- either I ll create a dedicated function for that, with copy-pasting the relevant desitarget lines
- or that could be done in the desitarget write_skies() and write_targets(), with adding an optional argument like populate_subpriority=True); I ll then keep using those routines, but with adding populate_subpriority=False.

I recall that those files are intermediary products, passed as inputs to actual fiber assignment; we don t svn-commit them, though we keep them around are they are useful (e.g. to estimate the correct per-tile elgxqso weights for elg analysis).
but I m not really sure of the importance of the header content, hence asking you.

thanks!

example of additional header keywords:
```
DEPNAM00= 'desitarget'                                                          
DEPVER00= '1.0.1   '                                                            
DEPNAM01= 'desitarget-git'                                                      
DEPVER01= 'unknown '                                                            
DEPNAM02= 'photcat '                                                            
DEPVER02= 'X       '                                                            
DEPNAM03= 'tractor-files'                                                       
DEPVER03= '/global/cfs/cdirs/desi/survey/ops/surveyops/trunk/mtl/main/dark'     
DEPNAM04= 'tractor-files-2'                                                     
DEPVER04= '/global/cfs/cdirs/desi/target/catalogs/dr9/1.0.0/targets/main/resol&'
CONTINUE  've/dark '                                                            
DEPNAM05= 'qso-selection'                                                       
DEPVER05= 'unknown '                                                            
SURVEY  = 'main    '                                                            
RESOLVE =                    T                                                  
MASKBITS=                    T                                                  
BACKUP  =                    F                                                  
DR      =                                                                       

```

**Comment by geordie666** [comment]
@araichoor: [desitarget 734](https://github.com/desihub/desitarget/pull/734) already contains the option you're discussing. You can pass a [subpriority=False keyword](https://github.com/desihub/desitarget/pull/734/commits/9a63bf3da20509541b1943e13439e003c630d691) to turn off any `SUBPRIORITY` over-writing behavior.

**Comment by araichoor** [comment]
awesome! I think I ll just add this subpriority=False in the calls to write_skies() and write_targets().

**Comment by geordie666** [comment]
I was hoping to get feedback from Aaron on that branch before merging it. But, I can merge it fairly soon anyway and fix anything later for the GFAs.

Note that there is a minor complication here, in that @sbailey has also implemented a similar idea in [desitarget 736](https://github.com/desihub/desitarget/pull/736). But, in any case, the functionality you need should exist soon in desitarget.

**Comment by araichoor** [comment]
I think there is no rush, as long as we do this before the start of next lunation, right?

**Comment by geordie666** [comment]
Right, although the next lunation is already creeping up on us!

**Comment by araichoor** [comment]
This is addressed in https://github.com/desihub/fiberassign/pull/366.
Closing.
