### ISSUE TITLE
Invalid SS and SF input files silently ignored, giving zero SS and SF in output?

### ISSUE THREAD

**Issue by apcooper** [desihub/fiberassign#38]
I'm confused about how the sky and standard inputs are specified for fiberassign. 

I thought it was via the SStarsfile and SkyFfile paths in the features file -- I've been using some ascii files for this (don't know where these came from, I must have inherited them from an earlier version). Everything seemed to be working OK. However, I've just noticed that these files were not actually being read, and I was unknowingly ending up with no skys or standards. 

The reason for this is that at the top of fiberassign.cpp the files are being read with structs.cpp:read_MTL_file(), which passes through silently when the target path isn't readable by cfitsio.

I have a partial fix for this already that adds some sanity checks for the existence and reading of targFile,  SStarsfile and SkyFfile (the current version runs to completion  even if it can't read the target file -- was that intended?). Can someone please clarify whether or not the SStarsfile and SkyFfile are supposed to be FITS? And if so does anyone know where I can get FITS versions of those files?

**Comment by rncahn** [comment]
Can you send me the features file you are using?

Bob Cahn

**Comment by apcooper** [comment]
Attached. 

[bt_features_apc.txt](https://github.com/desihub/fiberassign/files/249185/bt_features_apc.txt)

**Comment by rncahn** [comment]
Well, I think the SS and SF files should be in fits.  Here is a features
file from master on github:

Targfile /project/projectdirs/desi/mocks/preliminary/mtl/v2/mtl-lite.fits
SStarsfile
/project/projectdirs/desi/mocks/preliminary/mtl/v2/stdstars-lite.fits
SkyFfile  /project/projectdirs/desi/mocks/preliminary/mtl/v2/sky-lite.fits
Secretfile
/project/projectdirs/desi/mocks/preliminary/mtl/v2/truth-lite.fits
surveyFile test/default_survey_list.txt
tileFile
/project/projectdirs/desi/software/edison/desimodel/0.3.1/data/footprint/desi-tiles.par
fibFile
/project/projectdirs/desi/software/edison/desimodel/0.3.1/data/focalplane/fiberpos.txt
outDir {outdir}/

PrintAscii true
PrintFits true
diagnose true

kind QSOLy-a QSOTracer LRG ELG FakeQSO FakeLRG SS SF
type QSO QSO LRG ELG QSO LRG SS SF
prio 3400 3400 3200 3000 3400 3200 0 0
priopost 3500 0 3200 0 0 0 0 0
goal 5 5 2 1 5 2 5 5
goalpost 5 1 2 1 1 1 5 5
lastpass 0 0 0 1 0 0 1 1
SS       0 0 0 0 0 0 1 0
SF       0 0 0 0 0 0 0 1
pass_intervals 0 50 100 150 200

Randomize false
Pacman false
Npass 5
MaxSS 10
MaxSF 40
PlateRadius 1.65
InterPlate 0
Analysis 0
InfDens false

TotalArea 15789.0
invFibArea 700
moduloGal 1
moduloFiber 1

Collision false
Exact true
AvCollide 3.2
Collide 1.98
NoCollide 7.0
PatrolRad 5.8
NeighborRad 14.05

PlotObsTime false
PlotHistLya false
PlotDistLya false
PlotFreeFibHist false
PlotFreeFibTime false
PlotSeenDens false
PrintGalObs false


MinDec -10.
MaxDec 10.
MinRa 0.
MaxRa 10.
Verif false

Please keep me informed of your progress.  I need to make sure the code
really works for the users.

Bob Cahn

**Comment by apcooper** [comment]
Hi Bob, 

Thanks for the pointers to the latest FITS-format SS and SF files, everything works OK with those. I've submitted a PR with some checks to avoid invalid/missing MTL files being accepted without complaint -- maybe that behavior was an intentional feature, in which case perhaps it should be an explicit switch somewhere rather than the default?

**Comment by apcooper** [comment]
Closed after merge of https://github.com/desihub/fiberassign/pull/39
