### ISSUE TITLE
April 10th 2021 rundate issue

### ISSUE THREAD

**Issue by ashleyjross** [desihub/fiberassign#384]
In order to reproduce 20210410 SV3 fiberassign results, a rundate that is earlier than what is in the header of the fiberassign results is required. There was a hardware update just prior to the run and it is likely that the desimodel focalplane state was changed in svn but not updated at NERSC prior to running fiberassign.

In code, the fix is very easy (e.g., in python):
    rundate= fiberassign_header['RUNDATE']
    if rundate == '2021-04-10T21:28:37':
        rundate = '2021-04-10T20:00:00'
and then pass rundate to fiberassign. 

But, we might want a more complete fix.

**Comment by araichoor** [comment]
fixed in fba_rerun_io.py in https://github.com/desihub/fiberassign/pull/398.
