### ISSUE TITLE
Reproducibility in reading the ToO.ecsv ledger

### ISSUE THREAD

**Issue by araichoor** [desihub/fiberassign#393]
The original pre-shutdown 2020 Main ToO.ecsv file (and SV3) do not have a TIMESTAMP column.

That is potentially problematic to rerun fiber assignment, as the ToO.ecsv file will evolve.
See https://github.com/desihub/desitarget/pull/761.

**Comment by araichoor** [comment]
ah right, sorry I forgot about that TILE/FIBER type (even though you reminded it to me recently...)
thanks a lot for bringing that up!

I should then apply this TIMESTAMP cut only if `too_tile=False` in this create_too() function, ie when designing Main-survey tiles:
https://github.com/desihub/fiberassign/blob/802de4c853c29d104a676d925b74bda177989ab6/py/fiberassign/fba_launch_io.py#L1184-L1186
right?
That should solve the issue with no action needed on your side?

And a clarification: I m a bit confused by your message: there is only one ToO.ecsv file, right (in $DESI_SURVEYOPS/mtl/main/ToO/)? that file will contain TOO_TYPE=TILE or FIBER targets (though for now, only TILE are there).

**Comment by geordie666** [comment]
Correct, I think that if you only apply the `TIMESTAMP` for `TOO_TYPE==FIBER` targets, then everything will be OK.
```
And a clarification: I m a bit confused by your message: there is only one ToO.ecsv file, right (in $DESI_SURVEYOPS/mtl/main/ToO/)? that file will contain TOO_TYPE=TILE or FIBER targets (though for now, only TILE are there).
```
Everything you say in the above is correct (there is also a ToO ledger in `$DESI_SURVEYOPS/mtl/sv3/ToO/`, but that's irrelevant to this discussion.

**Comment by araichoor** [comment]
This is addressed in the merged https://github.com/desihub/fiberassign/pull/394.
