### ISSUE TITLE
ToO: reproducibility of the MJD window

### ISSUE THREAD

**Issue by araichoor** [desihub/fiberassign#395]
Pinging @sbailey and @schlafly for advice.

For assignment, ToOs are selected based on a cut on `MJD_BEGIN`, `MJD_END`, with defining a desired MJD window.
In the current fba_launch code, we first define `mjd_now` based on `Time.now()`:
https://github.com/desihub/fiberassign/blob/feab4ed8b8ce8f0568c91b91213e698198c4a0ec/bin/fba_launch#L650
Then we define the MJD window (`mjd_min`, `mjd_max`) based on `mjd_now`:
https://github.com/desihub/fiberassign/blob/feab4ed8b8ce8f0568c91b91213e698198c4a0ec/bin/fba_launch#L266-L267.

Using `Time.now()` to define `mjd_now` prevents reproducibility, when re-running fiberassign at a later time.
This is addressed in the fba_rerun3 branch, where we switched to using `args.pmtime_utc_str` to define `mjdnow`:
https://github.com/desihub/fiberassign/blob/2027fbbdf913a1a37526fc3861edc2c826fa8f12/bin/fba_launch#L111-L115
taking advantage that, up to now, `args.pmtime_utc_str` tracks when the code was actually run.

However, in a soon-to-be-merged PR, we introduced a new keyword in the fiberassign-TILEID.fits.gz header, `NOWTIME`, arguing that it is not a safe choice to assume that `args.pmtime_utc_str` tracks when the code was run (https://github.com/desihub/fiberassign/pull/392).

I can imagine two approaches to have things more consistent:
- **approach_1**: we add to fba_launch a `args.nowtime` argument  (defaulting to Time.now()), and tie `mjd_now` to this `args.nowtime`; the minor drawback is that, doing this, `args.nowtime` will track when the code was **originally** run, i.e. for a re-run it will not track when the re-run is done; that seems ok to me;
- **approach_2**: we add to fba_launch two arguments, `args.mjd_min` and `args.mjd_max` (defaulting to `Time.now()-1`, `Time.now()+30)`, and propagate those in the fiberassign-TILEID.fits.gz header; and get rid of `mjd_now`.

Of course, I m open to other solutions.

**Comment by schlafly** [comment]
Can we foresee a future when the ToO requests will be different from Time.now() - 1 and Time.now() + 30?  If so, let's do approach 2.  I hate adding more arguments, but the ToO stuff does sound rather different from just "now."

**Comment by araichoor** [comment]
thanks for the prompt feedback.
I don t really know for the -1, +30 values; I don t recall right now how the decision was made for those values, but it sounds not impossible to me that those could change in the future.
probably @geordie666 or @djschlegel have a better insight.

**Comment by schlafly** [comment]
And, just trying to understand what we're doing... the ToO file
https://desi.lbl.gov/svn/data/surveyops/trunk/mtl/main/ToO/ToO.ecsv
specifies an MJD_BEGIN and an MJD_END.  I'd have guessed these were the MJDs where a spectrum of the ToO would be of interest.  Moving forward to fa-on-the-fly, we hope that we're observing the tile ~immediately after we design it.  So I might have guessed that create_too would be fine with just one argument, the time we expect to observe the tile---we don't need another window?

And yeah, unfortunately, we want NOWTIME to be the runtime, I think.  So that argues either for making the one argument to create_too to be a new time, TOOTIME, or PMTIME, if we're happy overloading PMTIME as roughly "the time the tile was intended to be observed".

**Comment by djschlegel** [comment]
If still open for discussion, I would also prefer option (2).  Let's preserve TIMENOW as informational-only.

**Comment by geordie666** [comment]
I think @schlafly is correct about the philosophy of `MJD_BEGIN` and `MJD_END`. We really want those to define a window of time during which the ToO can be observed. If the time that we expect to observe the tile is within the range `MJD_BEGIN` to `MJD_END` then the ToO is a viable observation.

I think we hacked in the `Time_now()+30` for SV as we weren't necessarily sure when the tile would be observed.

**Comment by schlafly** [comment]
Thanks.  Okay, @anand, I'd propose making PMTIME either the one argument to create_too or both the mjd_min and mjd_max arguments.  That assumes that we only ever want to set the PMTIME to be the expected time of observation, which sounds reasonable to me.  If we can foresee a world where we wouldn't want PMTIME to be the expected time of observation, let's add an additional argument TOOTIME.

Let's not save two arguments for the TOOTIME min/max unless we need to for reproducibility / compatibility reasons with past fa runs.

**Comment by araichoor** [comment]
[remark: my github identifier is @araichoor :)]

ok perfect, I ll keep tying `mjd_now` to `PMTIME` (i.e. as currently done in fba_rerun3).

and what about the MJD window?
currently it is define based on the `mjd_min=mjd_now-1`, `mjd_max=mjd_now+30`:
https://github.com/desihub/fiberassign/blob/feab4ed8b8ce8f0568c91b91213e698198c4a0ec/py/fiberassign/fba_launch_io.py#L1250

following @schlafly s comment and @geordie666 s answer, it sounds like we d like to switch to a simple:
`keep &= (d["MJD_BEGIN"] <= mjd_now) &  (d["MJD_END"] >= mjd_now)`
no?

**Comment by geordie666** [comment]
Yes, that `keep` update looks correct to me. This seems the most efficient approach for ToOs if we're assigning tiles on a frequent basis.

**Comment by araichoor** [comment]
ok great.
I think I ll make a dedicated PR to:
- tie `mjd_now` to `PMTIME`
- update the MJD selection with: `keep &= (d["MJD_BEGIN"] <= mjd_now) & (d["MJD_END"] >= mjd_now)`

that sounds cleaner/more trackable.

then the fba_rerun3 branch would just contain changes for re-run, so should not be a blocking factor to make some tests at KPNO.

**Comment by araichoor** [comment]
For info, I ve submitted the following PR: https://github.com/desihub/fiberassign/pull/396.

**Comment by araichoor** [comment]
This is addressed in the merged https://github.com/desihub/fiberassign/pull/396.
