### ISSUE TITLE
STD_WD included in the per-petal STD counting

### ISSUE THREAD

**Issue by araichoor** [desihub/fiberassign#410]
Apparently, for the main survey, fiberassign considers as "STD", to fulfill the --standards_per_petal requirement: STD_WD, STD_BRIGHT, STD_FAINT.
However, the reduction pipeline is not using STD_WD; so one wants to discard STD_WD from this counting.

My understanding:
- fiberassign.targets.default_main_stdmask() has this list of masks: https://github.com/desihub/fiberassign/blob/33c15ad9904091d185e6329a7f6f6e2575e81ed1/py/fiberassign/targets.py#L230-L237
- then objects passing those masks are defined as TARGET_TYPE_STANDARD, which used by the c++ code.

Removing that line: https://github.com/desihub/fiberassign/blob/33c15ad9904091d185e6329a7f6f6e2575e81ed1/py/fiberassign/targets.py#L235
should address that.
Though, one has to be careful to preserve backward-compatibility.

**Comment by araichoor** [comment]
[discussion potentially also relevant for https://github.com/desihub/fiberassign/issues/411]

The non-trivial point here is to ensure backward-compatibility.
I m not sure to see how we can avoid to add a switch on a date (nowtime? rundate? mtltime? ...).

_Note that we would then need to make sure that the cut off date in the PR is before we actually design the tiles with the new tagged version; or pick a cut off date later in the future._

@sbailey also suggested during yesterday s telecon to make some dates (`rundate`?) a global variable throughout fiberassign.

I ve looked at the code: one way to go would be to propagate the `rundate` down to the `fiberassign.targets.default_main_stdmask()` function, `rundate` being an argument of `fiberassign.scripts.assign.parse_assign()`.

in `fiberassign.bin.fba_run`:
    `args = fiberassign.scripts.assign.parse_assign()` # rundate is one of the arguments

in `fiberassign.scripts.assign.run_assign_bytile()` or `fiberassign.scripts.assign.run_assign_full()`:
    `hw, tiles, tgs, tagalong = run_assign_init(args, plate_radec=plate_radec)`

then the flow of functions successively called in `run_assign_init()`, where one would need to propagate `rundate`:
https://github.com/desihub/fiberassign/blob/33c15ad9904091d185e6329a7f6f6e2575e81ed1/py/fiberassign/targets.py#L1030-L1033
which calls:
https://github.com/desihub/fiberassign/blob/33c15ad9904091d185e6329a7f6f6e2575e81ed1/py/fiberassign/targets.py#L829-L831
which calls:
https://github.com/desihub/fiberassign/blob/33c15ad9904091d185e6329a7f6f6e2575e81ed1/py/fiberassign/targets.py#L672
and:
https://github.com/desihub/fiberassign/blob/33c15ad9904091d185e6329a7f6f6e2575e81ed1/py/fiberassign/targets.py#L614
which both call:
https://github.com/desihub/fiberassign/blob/33c15ad9904091d185e6329a7f6f6e2575e81ed1/py/fiberassign/targets.py#L230

**Comment by araichoor** [comment]
Shall I try that?

**Comment by araichoor** [comment]
@schlafly @schlegel: given that no suggestion came up, I ll go ahead and implement what I suggest, i.e. add a `if rundate < rundate_cutoff: ... else: ...` switch in `default_main_stdmask()`, with propagating the rundate argument down to that function.
I can do that ~now.
Note that I ll also do something similar to solve the issue https://github.com/desihub/fiberassign/issues/411, i.e. propagate down to `default_main_stdmask()` the program argument, and discard 18<G<19 STD_FAINT if program=bright; I plan to make two separate PRs.

One last thing, @schlafly: for both those fixes, I need to choose a cutoff date.
I m thinking to pick tomorrow noon pacific (2021-10-01T19:00:00+00:00, if I m correct), so that:
- I merge the PRs + make a fiberassign/5.4.0 tag today (maybe tonight);
- we can test tomorrow morning and just after 12pm that it works properly at KPNO;
- AP switches to fiberassign/5.4.0 for tomorrow night.
Would that sound ok to you? Or would you like to proceed differently?

**Comment by schlafly** [comment]
For the STD_BRIGHT vs STD_FAINT thing, I haven't fully understood if we're doing what we want.  My sense is that we'd rather have brighter standards than fainter standards always.  If such a change were made I don't think we'd want to get rid of STD_FAINT for BRIGHT; they're just a fall back if not enough standards are available.

In practice we're taking both with no priorities, but it's not obvious to me that we wouldn't like the faint ones on BRIGHT tiles if no bright ones were available.

**Comment by schlafly** [comment]
The alternative to passing rundate through the long call stack would be to specify stdmask at the top of that call stack.  That would have the negative consequence that the default is wrong, but would save passing a new argument through a long call stack.  Your call.

**Comment by araichoor** [comment]
thanks for the suggestion; I think I ll keep the rundate propagation, as we ll also need that for the STD_BRIGHT/STD_FAINT change.
btw, I "transfer" that discussion about standards to https://github.com/desihub/fiberassign/issues/411.

**Comment by araichoor** [comment]
I m thinking to add a small function to control this cutoff date.
It would have the advantage that it can be queried throughout the code.
For this specific case, I d also need to use that cutoff date in `fba_launch_io.py,` when producing the qa plot.

But I can imagine it can be useful in the future, as we may face other cases where we would implement changes with a check on some date (rundate, mtltime, etc); we would then just have add another "case" to that function, which would centralize all such cutoff dates, rather than being scattered across the scripts.

It currently looks like as follows, and I m putting that utility function in `fba_launch_io.py`:
```
def get_date_cutoff(case):
    """Returns cutoff date for some assignment decision.
                                                                                                                                                                  
    Args:
        case: "rundate_std_wd" (string)

    Notes:
        "rundate_std_wd":
            "2021-10-01T19:00:00+00:00"
            include or not STD_WD in default_main_stdmask()
            https://github.com/desihub/fiberassign/pull/XXX
    """
    if case == "rundate_std_wd":
        return "2021-10-01T19:00:00+00:00"

```

**Comment by araichoor** [comment]
This issue has been addressed with PR https://github.com/desihub/fiberassign/pull/415.
Closing it.
