### ISSUE TITLE
patch svn fiberassign with FLUX_IVAR_W1/W2

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#424]
Fiberassign files generated before 20210316 (I think those prior to tag 2.1.1) do not have FLUX_IVAR_W1 and FLUX_IVAR_W2 even for targets where they are available in the input target files.  It would be really convenient downstream if we could patch the fiberassign files in svn to include these columns, at least for sv1 tiles.  Currently desispec patches these at the very end when stacking redshift catalogs, but all other intermediate products have dummy values for those columns (added as -1 by assemble_fibermap).

If we decide *not* to patch these in fiberassign svn, then let's punt this over to desispec and consider patching the values during assemble_fibermap instead of post-factor during desi_zcatalog.

See desihub/desispec#1717 for more context.

**Comment by araichoor** [comment]
The PR https://github.com/desihub/fiberassign/pull/436, used to do the second patching the fiberassign files, fixes the above, with adding the FLUX_IVAR_W1, FLUX_IVAR_W2 columns.
Those patched fiberassign files will shortly be committed to svn, and will be used by future desispec productions (himalayas? iron, etc).
