### ISSUE TITLE
incomplete docstring for load_targets_table

### ISSUE THREAD

**Issue by forero** [desihub/fiberassign#429]
While trying to update this notebook 

https://github.com/desihub/tutorials/blob/39ab3f17a648322e44c7ab932eead2edaeb335f8/FiberAssignAlgorithms_Part1.ipynb

to work under the 22.2 kernel, I found that the function `load_targets_table` now has three required inputs, instead of the two provided in the notebook. The new input seems to be `tagalong`, but the docstring in `load_targets_table` does not describe what `tagalong` is, making it difficult to correctly patch the notebook.

**Comment by araichoor** [comment]
I think you re correct, the new entry is `tagalong`.
I believe that s been introduced by @dstndstn in this PR https://github.com/desihub/fiberassign/pull/353.
From a quick look at `target.py`, it looks that this newly introduced argument `tagalong` does not appear in the docstr of other functions (e.g. `load_target_file()`).

@dstndstn : do you confirm? if so, one should update the docstr.
If you prefer, I could do that update.
I may just need from your side a generic description of this `tagalong`; i.e. something similar to:
```
tgs (Targets): The targets object to modify.
```

Thanks.

**Comment by araichoor** [comment]
The PR https://github.com/desihub/fiberassign/pull/430 addresses this ticket.
