### ISSUE TITLE
Do we need to keep merged branches in fiberassign?

### ISSUE THREAD

**Issue by weaverba137** [desihub/fiberassign#448]
Fiberassign currently has *many* branches, which makes it difficult to find any particular inactive branch.  Normal procedure in other DESI packages is to delete a branch immediately after merging an associated pull request.  Is there a specific reason *not* to do this with fiberassign?  If so, that should be documented.  If not, then there would be no objection to deleting merged branches.

**Comment by araichoor** [comment]
my bad, I ve not followed that habit.
I suspect most of those could be deleted.
I ll take care of that.

I actually planned to make a cleaning of the repo with things like that, triage the issues, etc; that is what I started with the PR on doc/changes.rst.

**Comment by araichoor** [comment]
I ve deleted all merged branches.
23 branches are left: I ll take a closer look at those.

**Comment by weaverba137** [comment]
Update: there are no longer any stale branches associated with merged pull requests (thank you @araichoor!). However, there are about 5 or so that are associated with *deleted* pull requests.  Do we need to keep those?

**Comment by weaverba137** [comment]
In the interest of spring cleaning, I'm pinging this ticket. There are still branches associated with deleted pull requests, as well as a branch associated with a merged pull request. And overall, there are just *many* branches. What clean-up can be done?

**Comment by araichoor** [comment]
sorry for the late handling of this one.
I m always uncertain about deleting branches here, as I fear that there could be some useful piece of code in there that would be lost if the branch is deleted…
except branches from @dstndstn, those pre-date the sv1 survey, so they are very likely deprecated.

I suggest to delete the branches listed below, except https://github.com/desihub/fiberassign/tree/patch-fa-2 and https://github.com/desihub/fiberassign/tree/qa_fiberassign_with_p.
in case, I pinged below the branch authors: let s say that if I don t hear from you by this Friday, I ll just go ahead and delete.

@dstndstn [2022, Jun.] https://github.com/desihub/fiberassign/tree/patch-fa-2
=>
that code was used in the end? probably, I ll have to check; if so, we ll want to merge that branch, I think

@dstndstn  [2021, Jun.] https://github.com/desihub/fiberassign/tree/add-fits-compare
=>
you were "duplicating" the fitsdiff command (https://github.com/desihub/fiberassign/pull/377)
ok to delete?

@dstndstn  [2021, Jun.] https://github.com/desihub/fiberassign/tree/speedups2
=>
I *think* it s kind of the same code that was merged here https://github.com/desihub/fiberassign/pull/378?
ok to delete?

@dstndstn  [2021, Jun.] https://github.com/desihub/fiberassign/tree/gaia-only-targetids
=>
aborted PR here https://github.com/desihub/fiberassign/pull/374.
ok to delete?

@dstndstn  [2021, May] https://github.com/desihub/fiberassign/tree/excl-on-demand
=>
mmmhh.. I m not sure what superseded that...
ok to delete?

@forero  [2020, May] https://github.com/desihub/fiberassign/tree/join_results
=>
deprecated, ok to delete?

@rncahn  [2019, Feb.] https://github.com/desihub/fiberassign/tree/efficiency_test
=>
deprecated, ok to delete?

@sbailey  [2019, Jan] https://github.com/desihub/fiberassign/tree/legacy
=>
not sure what it is :) deprecated anyway, ok to delete?

@akrolewski  [2018, Oct.] https://github.com/desihub/fiberassign/tree/qa_fiberassign_with_p
aborted PR here https://github.com/desihub/fiberassign/pull/148.
maybe some still useful plotting code, I suggest to keep it for now

@forero  [2018, Aug.] https://github.com/desihub/fiberassign/tree/new_inputs
=>
not sure what it is :) deprecated anyway, ok to delete?

@rncahn  [2016, Aug.] https://github.com/desihub/fiberassign/tree/for_joe_silber
=>
some cpp changes; probably deprecated, ok to delete?

**Comment by dstndstn** [comment]
Hi Anand, Thanks for doing this!  I agree with all your assessments!

**Comment by sbailey** [comment]
I deleted the legacy branch, which was the only one assigned to me.

**Comment by forero** [comment]
I deleted join_results and new_inputs. Thanks!

**Comment by araichoor** [comment]
thanks all for your answers/actions.
I ve deleted the branches I suggested I would.
there are now three branches only.

@weaverba137: is it ok to consider the issue solved and close the ticket? (thanks for your patience on that!)

**Comment by weaverba137** [comment]
Yes, OK to close.

**Comment by araichoor** [comment]
perfect, thanks.
