### ISSUE TITLE
fiberassign on Read the Docs: no recent, stable version compiles successfully

### ISSUE THREAD

**Issue by weaverba137** [desihub/fiberassign#450]
There are no recent tags of fiberassign that compile *documentation* successfully on Read the Docs. I tested 5.4.0, 5.5.0, 5.6.0 and 5.7.0. On the other hand, the 'latest' version does compile successfully.

One solution would be to create a 5.7.1 tag.

**Comment by araichoor** [comment]
If I m correct, since 5.7.0, the only changes are:
- the merged PR is https://github.com/desihub/fiberassign/pull/440, where @weaverba137 did all the cleanup (thanks again!)
- this commit: https://github.com/desihub/fiberassign/commit/270b4e80c53d94e48c54a9448d32c3e6b7ec90d5 ("master to main in setup.py")

@sbailey : shall I go ahead and create a 5.7.1 tag? (I can do that this afternoon).

**Comment by weaverba137** [comment]
In the latest checkout, there are some warnings about fiberassign objects that are mocked *internally*, and theses are not explicitly mocked in the `doc/conf.py` file.
```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v4.5.0
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from https://matplotlib.org/objects.inv...
loading intersphinx inventory from https://docs.astropy.org/en/stable/objects.inv...
loading intersphinx inventory from https://docs.h5py.org/en/latest/objects.inv...
intersphinx inventory has moved: https://matplotlib.org/objects.inv -> https://matplotlib.org/stable/objects.inv
intersphinx inventory has moved: https://docs.scipy.org/doc/scipy/reference/objects.inv -> https://docs.scipy.org/doc/scipy/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 12 source files that are out of date
updating environment: [new config] 12 added, 0 changed, 0 removed
reading sources... [100%] usage                                                                                                                                 
WARNING: A mocked object is detected: 'fiberassign.hardware.Hardware'
WARNING: A mocked object is detected: 'fiberassign.tiles.Tiles'
WARNING: A mocked object is detected: 'fiberassign.targets.Target'
WARNING: A mocked object is detected: 'fiberassign.targets.Targets'
WARNING: A mocked object is detected: 'fiberassign.targets.TargetsAvailable'
WARNING: A mocked object is detected: 'fiberassign.targets.LocationsAvailable'
WARNING: A mocked object is detected: 'fiberassign.assign.Assignment'
WARNING: A mocked object is detected: 'fiberassign.utils.Circle'
WARNING: A mocked object is detected: 'fiberassign.utils.Segments'
WARNING: A mocked object is detected: 'fiberassign.utils.Shape'
WARNING: A mocked object is detected: 'fiberassign.utils.Logger'
WARNING: A mocked object is detected: 'fiberassign.utils.Timer'
WARNING: A mocked object is detected: 'fiberassign.utils.GlobalTimers'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] usage                                                                                                                                  
generating indices... genindex done
highlighting module code... [100%] fiberassign.utils                                                                                                            
writing additional pages... search done
copying images... [100%] _static/plot_assign.png                                                                                                                
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 13 warnings.

The HTML pages are in _build/html.

Build finished. The HTML pages are in _build/html.
```

**Comment by weaverba137** [comment]
Oops, I think you should ignore my previous comment, I think I forgot to actually compile the C++ code before running the test.

**Comment by weaverba137** [comment]
I recommend we make a trivial change to the current main branch to trigger a GitHub Actions build before tagging. This would probably be sufficient:

* Update `doc/changes.rst`.
* Update `_version.py`.

Assuming everything still builds successfully, then commit the tag.

**Comment by araichoor** [comment]
Apologies, but as I m not familiar with those, could you detail what updates you re meaning?
When I create a tag, I follow those steps:
- https://desi.lbl.gov/trac/wiki/Computing/Software/Guidelines#BeforeYouTag
- https://desi.lbl.gov/trac/wiki/Computing/Software/Guidelines#Updateversionandmaketag
- https://desi.lbl.gov/trac/wiki/Computing/Software/Guidelines#AfterYouTag

The "Updateversionandmaketag" guidelines include some update of `doc/changes.rst` and of `_version.py`: are you referring to those steps? Or something else?

Thanks.

**Comment by weaverba137** [comment]
Yes, please follow the steps in https://desi.lbl.gov/trac/wiki/Computing/Software/Guidelines#Updateversionandmaketag.

The important thing is to push the commits to `main` and wait for all tests to pass before creating the tag.

**Comment by araichoor** [comment]
@weaverba137: I ve tagged + installed at cori/perlmutter `fiberassign/5.7.1`.
I hope that everything is right now.
(ps: it takes a while, as there are 3 commits in the procedure, and the tests take ~20min to execute)

**Comment by weaverba137** [comment]
Thank you, I will test that tag on ReadtheDocs momentarily.

**Comment by weaverba137** [comment]
5.7.1 is now compiled as 'stable' on ReadTheDocs, https://fiberassign.readthedocs.io/en/stable/. Closing this ticket, but let's be sure to keep an eye on the documentation status of this package.
