### ISSUE TITLE
EDR/fuji: proper-motion correction applied in fiberassign for most of sv1 tiles

### ISSUE THREAD

**Issue by araichoor** [desihub/fiberassign#455]
for the sake of documentation, opening an "issue" here - which I ll close with this comment.

as we know, we did apply proper-motion correction at the fiberassign step at the beginning of sv1.
I believe this changes the following columns: TARGET_{RA,DEC}, REF_EPOCH, PLATE_{RA,DEC} (note that I think that this does not apply e.g. for sky targets).
an unfortunate consequence is that the value in those columns can thus differ from what s in the desitarget catalogs.

from the small piece of code below, we did apply this for:
- the `cmxm33` tile: 80615;
- all the sv1 tiles, except the four `sv1dc3r2` tiles: 80971, 80972, 80974, 80975 (note: 80973 and 80976 also, but those were never observed).

and we did not apply proper-motion correction for any sv2, sv3 tiles (nor later).

code snippet:
```
# first grab the max(REF_EPOCH) for each tile, and the number of occurences
d = Table.read("/global/cfs/cdirs/desi/spectro/redux/fuji/tiles-fuji.csv")
d["REF_EPOCH_MAX"], d["NOBJ_REF_EPOCH_MAX"] = 0., 0
for i in range(len(d)):
    fn = "/global/cfs/cdirs/desi/target/fiberassign/tiles/trunk/{}/fiberassign-{:06d}.fits.gz".format("{:06d}".format(d["TILEID"][i])[:3], d["TILEID"][i])
    ref_epochs = fitsio.read(fn,ext="FIBERASSIGN",columns="REF_EPOCH")
    d["REF_EPOCH_MAX"][i] = ref_epochs.max()
    d["NOBJ_REF_EPOCH_MAX"][i] = (ref_epochs == ref_epochs.max()).sum()
```

sv1 started in Dec. 2020, so I use to identify tiles where proper-motion correction was applied in fiberassign.
```
sel = d["REF_EPOCH_MAX"] > 2020
sel.sum()
np.unique(d["SURVEY"][sel], return_counts=True)
```
returns:
```
185
(<Column name='SURVEY' dtype='str7' length=2>
cmx
sv1, array([  1, 184]))
```
and there are four sv1 tiles where we did not apply proper-motion correction in fiberassign:
```
sel = (d["REF_EPOCH_MAX"] <= 2020) & (d["SURVEY"] == "sv1")
d[sel]["SURVEY", "FAPRGRM", "FAFLAVOR", "TILEID", "REF_EPOCH_MAX", "NOBJ_REF_EPOCH_MAX"].pprint_all()
```
returns:
```
SURVEY FAPRGRM FAFLAVOR TILEID REF_EPOCH_MAX NOBJ_REF_EPOCH_MAX
------ ------- -------- ------ ------------- ------------------
   sv1   dc3r2 sv1dc3r2  80972        2015.5                852
   sv1   dc3r2 sv1dc3r2  80974        2015.5                966
   sv1   dc3r2 sv1dc3r2  80971        2015.5                975
   sv1   dc3r2 sv1dc3r2  80975        2015.5                850
```

**Comment by weaverba137** [comment]
Just one question just to document this explicitly:  For all of `fuji`, the TARGET_RA, TARGET_DEC and REF_EPOCH, *really are the same* as the Tractor values, except where noted above, correct?

**Comment by araichoor** [comment]
that s my expectation, but I haven t explicitly verified that.
I think @sbailey may have done something like that already... if not I can run that check if need be, please let me know.

**Comment by geordie666** [comment]
I don't think this is the case for _all_ files, although I've only really checked the `zall-pix-fuji.fits` file. From a [thread on Slack](https://desisurvey.slack.com/archives/C2AT2NEHY/p1684874330130329?thread_ts=1684862430.826799&cid=C2AT2NEHY) with @stephjuneau and @akremin:

Looking at, e.g., `TARGETID==39628438587315309` from `sv3/dark`: This target has `REF_EPOCH==0`  in the original targeting files (and the MTL ledgers) but `REF_EPOCH==2015.5` in the `zall-pix-fuji.fits` file. This suggests to me that the objects reported by Stephanie that have `PMRA==PMDEC==0` and `REF_EPOCH==2015.5` have had their `REF_EPOCH` updated to 2015.5 downstream of desitarget and during (or before) the construction of the `zall-pix-fuji.fits` file. This isn't necessarily problematic as any value of `REF_EPOCH` is valid in the ICRS for an object with exactly zero proper motion.

**Comment by araichoor** [comment]
ah crap; that s correct, @geordie666, *thanks* a lot for reminding that.

from a quick look at `fiberassign.fba_launch_io.py`, I indeed see several calls to this `force_nonzero_refepoch()` function, which does what you inferred (ie set `REF_EPOCH=2015.5` for objects with `PMRA=PMDEC=REF_EPOCH=0`).

so I guess I ll have to run some explicit checks... I put that on my to-do-list for next week.

note that this is currently applied in the main survey; e.g. a tile observed on 20230526:
```
grep setting /global/cfs/cdirs/desi/target/fiberassign/tiles/trunk/010/fiberassign-010985.log | grep objects
INFO: 17.4s	gfa	setting REF_EPOCH=2015.5 for 0 objects with REF_EPOCH=0
INFO: 20.4s	targ	setting REF_EPOCH=2015.5 for 29737 objects with REF_EPOCH=0
INFO: 26.4s	scnd	setting REF_EPOCH=2015.5 for 0 objects with REF_EPOCH=0
```
