### ISSUE TITLE
add python scripts to prepare a fiberassign run and process its results 

### ISSUE THREAD

**Issue by forero** [desihub/fiberassign#49]

**Comment by forero** [comment]
This is being worked out in branch `apc_mocks` following the work done in `desitarget:apc_mocks`.

**Comment by sbailey** [comment]
bin/config-fiberassign can generate a template fiberassign parameter file, e.g.
```
config-fiberassign  --mtl $SCRATCH/end2end/targets/mtl.fits \
    --stdstars $SCRATCH/end2end/targets/standards-dark.fits \
    --sky $SCRATCH/end2end/targets/sky.fits \
    --surveytiles $SCRATCH/end2end/fiberassign/dark-tiles.txt \
    --outdir $SCRATCH/end2end/fiberassign \
    --config $SCRATCH/end2end/fiberassign/fiberassign-config-dark.txt
fiberassign $SCRATCH/end2end/fiberassign/fiberassign-config-dark.txt
```
Does that do the functionality you were thinking of for this ticket?  If so, please close ticket.  If not, please update ticket with other features that you want.

**Comment by forero** [comment]
The new functionality is good enough. 

`Fiberassign` should itself run with the same command line options! I am closing this issue and opening a new one.
