### ISSUE TITLE
Reading input files from sweeps/bricks

### ISSUE THREAD

**Issue by forero** [desihub/fiberassign#52]
We would like to have the option to read many sweeps/bricks as input and not only a big monolithic input file. The discussion is also open to decide whether this enhancement would be inconvenient and should be dropped.

**Comment by apcooper** [comment]
I thought about this a bit after it came up in the desitarget thread and I couldn't really convince myself why it would be worth doing... you'd still have to read the same amount of data and construct this table inside fiberassign. And then it would be harder to figure out what order the input files got stacked into that internal table etc. etc. Am I missing something?

**Comment by forero** [comment]
I agree that 20GB is still OK and that it can be a pain to track what input files got into what sweep/brick. 

But this might have another upside: reading only the files for the patch of sky where you need to make the fiberassignment without having to create a new target file. 

We can come back to this issue in November/December and make a decision.

**Comment by apcooper** [comment]
An alternative solution would be to have a spatial index in the monolithic target file so that FA could read a subset of rows corresponding to the required patch of sky.

**Comment by forero** [comment]
Doesn't seem to be needed anymore.
