### ISSUE TITLE
Top level Makfile is not desiInstall compatible

### ISSUE THREAD

**Issue by weaverba137** [desihub/fiberassign#54]
The top-level Makefile defines `TOPDIR` and `INSTALL` in a way that is fine for development but incompatible with desiInstall.  The fix may be as simple as:

```Makefile
ifdef INSTALL_DIR
export INSTALL = $(INSTALL_DIR)
endif
```

See also the top-level specex Makefile for a fully desiInstall-compatible example.

**Comment by sbailey** [comment]
Please go ahead and fix this yourself and iterate with desiInstall until you have a working combination.  Thanks.

**Comment by sbailey** [comment]
PR #56 fixed this; I tagged 0.3.1 and tested it with a successful "desiInstall -v fiberassign 0.3.1".  Thanks.
