### ISSUE TITLE
Strange Python error while linking fiberassign executables

### ISSUE THREAD

**Issue by weaverba137** [desihub/fiberassign#55]
I got this strange warning while compiling fiberassign on Edison.
```
g++ -o fiberassign fiberassign.o collision.o feat.o global.o misc.o structs.o -fopenmp -L/global/common/edison/contrib/desi/conda/conda_3.5-20160913_extra/lib -lcfitsio -lm
/usr/lib64/python2.6/site-packages/pkg_resources.py:1054: UserWarning: /global/homes/b/bweaver/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
g++ -O3 -std=c++11 -fPIC -DNDEBUG -fopenmp -I. -I/global/common/edison/contrib/desi/conda/conda_3.5-20160913_extra/include -o surveysim.o -c surveysim.cpp
g++ -o fiberassign_surveysim surveysim.o collision.o feat.o global.o misc.o structs.o -fopenmp -L/global/common/edison/contrib/desi/conda/conda_3.5-20160913_extra/lib -lcfitsio -lm
/usr/lib64/python2.6/site-packages/pkg_resources.py:1054: UserWarning: /global/homes/b/bweaver/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
```
Note how this is Python 2.6, even though I have the DESI Python 3 environment installed.

**Comment by sbailey** [comment]
Is this reproducible?

In the past I've had an intermittent but not strictly reproducible case where our anaconda python executable was picking up the system python libraries under the hood.  After banging on it with NERSC consultants for awhile, the problem went away without a specific fix from either side.

**Comment by rncahn** [comment]
I tried compiling fiberassign on edison at 15:33 Nov. 10.

It didn't indicate any problem but the file size wasn't exactly the same as
when I compiled on Oct.10:

rncahn@edison08:~/garrigue/fiberassign> make install
make[1]: Entering directory `/global/u1/r/rncahn/garrigue/fiberassign/src'
g++ -O3 -m64 -fPIC -DNDEBUG -std=c++11 -fopenmp -I.
-I/global/common/edison/contrib/hpcosmo/hpcports_gnu-9.0/cfitsio-3.37_ef0bbcfa-9.0/include
-o fiberassign.o -c fiberassign.cpp
g++ -O3 -m64 -fPIC -DNDEBUG -std=c++11 -fopenmp -I.
-I/global/common/edison/contrib/hpcosmo/hpcports_gnu-9.0/cfitsio-3.37_ef0bbcfa-9.0/include
-o collision.o -c collision.cpp
g++ -O3 -m64 -fPIC -DNDEBUG -std=c++11 -fopenmp -I.
-I/global/common/edison/contrib/hpcosmo/hpcports_gnu-9.0/cfitsio-3.37_ef0bbcfa-9.0/include
-o feat.o -c feat.cpp
g++ -O3 -m64 -fPIC -DNDEBUG -std=c++11 -fopenmp -I.
-I/global/common/edison/contrib/hpcosmo/hpcports_gnu-9.0/cfitsio-3.37_ef0bbcfa-9.0/include
-o global.o -c global.cpp
g++ -O3 -m64 -fPIC -DNDEBUG -std=c++11 -fopenmp -I.
-I/global/common/edison/contrib/hpcosmo/hpcports_gnu-9.0/cfitsio-3.37_ef0bbcfa-9.0/include
-o misc.o -c misc.cpp
g++ -O3 -m64 -fPIC -DNDEBUG -std=c++11 -fopenmp -I.
-I/global/common/edison/contrib/hpcosmo/hpcports_gnu-9.0/cfitsio-3.37_ef0bbcfa-9.0/include
-o structs.o -c structs.cpp
g++ -o fiberassign fiberassign.o collision.o feat.o global.o misc.o
structs.o -fopenmp
-L/global/common/edison/contrib/hpcosmo/hpcports_gnu-9.0/cfitsio-3.37_ef0bbcfa-9.0/lib
-lcfitsio -lm
g++ -O3 -m64 -fPIC -DNDEBUG -std=c++11 -fopenmp -I.
-I/global/common/edison/contrib/hpcosmo/hpcports_gnu-9.0/cfitsio-3.37_ef0bbcfa-9.0/include
-o surveysim.o -c surveysim.cpp
g++ -o fiberassign_surveysim surveysim.o collision.o feat.o global.o misc.o
structs.o -fopenmp
-L/global/common/edison/contrib/hpcosmo/hpcports_gnu-9.0/cfitsio-3.37_ef0bbcfa-9.0/lib
-lcfitsio -lm
cp fiberassign fiberassign_surveysim
/global/u1/r/rncahn/garrigue/fiberassign/bin
make[1]: Leaving directory `/global/u1/r/rncahn/garrigue/fiberassign/src'
rncahn@edison08:~/garrigue/fiberassign> cd bin
rncahn@edison08:~/garrigue/fiberassign/bin> lsalt
total 872
-rwxr-x---  1 rncahn 355987 Nov 10 15:33 fiberassign_surveysim
drwxr-x---  3 rncahn   4096 Nov 10 15:33 .
-rwxr-x---  1 rncahn 356197 Nov 10 15:33 fiberassign
drwxr-x---  2 rncahn    512 Nov 10 15:32 saver
drwxr-x--- 13 rncahn  65536 Sep 12 14:19 ..
-rw-r-----  1 rncahn   3312 Jun  8 10:42 universal_tiling_sequence_images.py
-rw-r-----  1 rncahn   2288 Jun  8 10:42 plot_time_development.py
-rw-r-----  1 rncahn   4360 Jun  8 10:42 full_map_any_sky.py
-rw-r-----  1 rncahn   3429 Jun  8 10:42
elg_equatorial_stripe_first_order.py
-rw-r-----  1 rncahn   3052 Jun  8 10:42 default_survey_tiling_order.py
-rw-r-----  1 rncahn      0 Apr 26  2016 diff.
-rwxr-x---  1 rncahn   7198 Nov 17  2015 make_catalog_stars_fibers_only.py
-rwxr-x---  1 rncahn   6155 Nov 17  2015 make_catalog_only_stars.py
rncahn@edison08:~/garrigue/fiberassign/bin> cd saver/
rncahn@edison08:~/garrigue/fiberassign/bin/saver> lsalt
total 704
drwxr-x--- 3 rncahn   4096 Nov 10 15:33 ..
-rwxr-x--- 1 rncahn 355755 Nov 10 15:32 fiberassign_surveysim
drwxr-x--- 2 rncahn    512 Nov 10 15:32 .
-rwxr-x--- 1 rncahn 355965 Nov 10 15:32 fiberassign


The files in ./saver were created Oct. 10.

**Comment by forero** [comment]
Did anyone managed to reproduce this error @sbailey @rncahn ?

**Comment by rncahn** [comment]
I think this is not an issue.
