### ISSUE TITLE
use subpriority when selecting sky and stds

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#59]
As reported by Bob:

For stability of reproducibility, sky and std star assignments should also use the subpriority column to select the order in which they are assigned to fibers.  They currently use whatever order they come out of the KDTree, which is reproducible, but perhaps fragile.

**Comment by forero** [comment]
@rncahn is this fixed? are we using the subpriority column in the MTL input file?

**Comment by rncahn** [comment]
yes
