### ISSUE TITLE
add constructor for class target

### ISSUE THREAD

**Issue by rncahn** [desihub/fiberassign#8]
This may be causing some errors detected by valgrind.

**Comment by forero** [comment]
@rncahn has this been fixed?

**Comment by sbailey** [comment]
Assigning to @tskisner.  More broadly than original title and related to #35, run valgrind on fiberassign, assess warnings and errors, and fix them.  i.e. do general cleanup of C++ robustness, but avoid doing major cosmetic refactors.

**Comment by rncahn** [comment]
thanks.

**Comment by tskisner** [comment]
@sbailey and @rncahn, see comment on #35, which test case is best / most useful for this work?

**Comment by rncahn** [comment]
As my last note suggested, simply running fiberassign may not be
sufficient. I'm happy to help Kisner with this, but no doubt is a much
better valgrinder.

**Comment by tskisner** [comment]
I am looking for a test case, so that I can verify that code changes do not break existing functionality.  I assume there are no formal "unit tests", but it would be great to have a stand-alone script that can be run with some input files and verify that outputs are the expected result.  Or at least a script that runs fiberassign and I can write a separate script that compares outputs of current master to results from a branch when making changes.

**Comment by rncahn** [comment]
I will try to provide something that runs.

**Comment by rncahn** [comment]
fiberassign  --mtl
/global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/mtl.fits  --stdstar
/global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/standards-dark.fits
--sky      /global/cscratch1/sd/sjbailey/desi/dev/end2end/targets/sky.fits
--surveytiles  /global/cscratch1/sd/rncahn/keep_tiles_0_15_150_170
--footprint $DESIMODEL/data/footprint/desi-tiles.fits  --positioners
$DESIMODEL/data/focalplane/fiberpos.txt --outdir
/global/cscratch1/sd/rncahn/desi/dev/end2end/fiberassign  --fibstatusfile
/global/cscratch1/sd/sjbailey/desi/code/desitest/mini/fiberstatus.ecsv


try this.  I think you can get at my  file keep_tiles_0_15_150_170 .  You
need to put your own outdir

**Comment by tskisner** [comment]
After changes in #124, code compiles cleanly even with all warnings enabled ("-Wall").  And valgrind runs with no memory issues.  Closing this now.
