### ISSUE TITLE
fill unused fibers with stdstars and sky

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#82]
If there are any unused fibers after assigning all available science targets and meeting the standard star and sky fiber minimum requirements, fill any remaining unused fibers with standard stars and sky locations.  "BADSKY" (DESI_TARGET = 2**36) should be used as fillers of last resort (though we don't have these in the current mocks).

The input catalogs should be dense enough that every fiber should always have *something* it can point at.  We should consider it an error condition of the input catalogs if they don't provide that, though for now it would probably be useful if fiberassign would continue to output tile files anyway and let us clean it up after the fact until we are robustly working with sky catalogs that guarantee coverage.

**Comment by forero** [comment]
We should be using `newsky` files (i.e. `/project/projectdirs/desi/users/sjbailey/mocks/sky/0.1/newsky.fits`) that were implemented (https://github.com/desihub/desitarget/pull/219) to have more uniform sky locations.

**Comment by sbailey** [comment]
Those are for mocks; I moved them into /project/projectdirs//desi/mocks/uniformsky/0.1/uniformsky-2048-0.1.fits as a better long-term location.  With that file there should always be a sky target available.

Ultimately we need to test on sky locations derived from real data and fix cases where there aren't sky targets available.  Currently we only have real-data skies for a small patch of sky /project/projectdirs//desi/target/catalogs/targets-110-wskies-dr5.0-0.16.0.fits and we need some tools for interfacing the target catalog (which has science, skies, and standards all together) and fiberassign (which currently expects them to be in separate files).

**Comment by rncahn** [comment]
Stephen,
Let me know if you need help on any of the fiberassignment tasks.

Bob

**Comment by forero** [comment]
@sbailey This case looks similar to the `GFA` script, i.e. something that should be addressed primarily at the `desitarget` level (`select_targets` and `mtl`) by preparing the right files. 
My question is then what should we do if there aren't any targets available for a fiber? Simply prepare a new sky file and try again?

**Comment by rncahn** [comment]
What do we mean by "every fiber should have something it can point at"?  I
suppose we mean here only sky fibers and standard stars.  With 5000 fibers
on roughly 7.5 sq deg, we have 1.5 x 10^{-3} sq deg per fiber.
Thus a density of about 700/sq deg gives us an average of one per fiber.
Now the likelihood that a fiber has no target when the mean number is n, is
simply exp(-n).  Suppose we say that we can tolerate one fiber out of the
5000 not having a target.  Then we need n such that exp(-n)=1/5000.  That
gives me n=8.5 or 5100/sq deg.  In my simulations, I had used 1400 sky
fibers and 400 standard stars per square degree.  That gives about a 7.6%
probability that a fiber has no SS or SF target.

**Comment by sbailey** [comment]
To be clear: the issue with the current code is that if there aren't enough science targets, fiber assign will stop assigning skies and standards when it has reached the 40/10 budget per petal, even if there are still unassigned fibers that could be assigned to additional skies and standards.  But yes, @forero you are right that this could be handled in MTL instead of fiberassign itself by including sky and standards in the MTL file with very low priority.  I like that solution.

What to do if there really isn't any target (science or sky or std)?  Let's add a NOTARGET bit to the DESI_TARGET mask, and in the fiberassign output include something with TARGETID=-1, DESI_TARGET set to NOTARGET, and RA/DEC set to the center of the positioner +1mm in x (detail: due to slightly differing arm lengths, the positioners can't reach their exact center, thus the +1mm in x).  We can then catch these in `qa-fiberassign` to go back and fix them up in the target list if possible.  i.e. we should consider this to be an error condition, but not something that would crash fiberassign or otherwise cause it to not write output.

@rncahn sky locations are not be selected to match some mean density with Poisson fluctuations about that, which would indeed cause many fibers to not have any sky targets.  Instead, the sky is gridded into pixels smaller than a fiber patrol area, and a sky (or BADSKY) location is chosen within each pixel, thus guaranteeing coverage unless there really is no data for that patch of sky.  See desihub/desitarget#219 for a plot of this algorithm for mocks.

**Comment by forero** [comment]
@sbailey OK. I will start now to work on this.

**Comment by rncahn** [comment]
OK.  No problem with Poisson fluctuations if the distribution of sky fiber
targets isn't random.

I'm not sure that assigning SF and SS low priorities is a good approach.
It is easy to fix things so will fill all fibers by simply by removing the
lines of code that enforce the maximum on SF and SS.

**Comment by sbailey** [comment]
It is a little more complicated than just removing the upper limit because below that limit we should bump science targets if needed to achieve that limit, but after that limit it should just continue to fill any unused fibers but not bump anything else.

**Comment by rncahn** [comment]
It doesn't sound hard to me.

**Comment by forero** [comment]
I am finding that the minimal 400 sky fibers tend to be clustered on the focal plane. Is this a feature? a bug? or completely irrelevant?
![sky](https://user-images.githubusercontent.com/1848618/36319673-a7a0cf20-1311-11e8-9742-750897d28c79.png)

**Comment by rncahn** [comment]
Not a feature!  Why are there so many unassigned fibers in the plot at the
lower right?  I suspect that no effort was made to randomize locations for
assigning SF and SS because it was imagined that there wouldn't be many
open fibers when we got around to making these assignments. They would
simply go in whatever holes there were and after that we replace
target-assigned fibers to SS and SF.  This is quite changed if you start
with a plate with many unassigned fibers.  I would have to look at the
code, but I can imagine that we work our way through each petal in some
order specified by the fiber number.  If the fiber numbers are not
randomized with respect to location, we could have the result you show.

**Comment by forero** [comment]
There are many unassigned fibers because I tried a very low number density for the targets. For a realistic number density the sky positions look random
![sky_two](https://user-images.githubusercontent.com/1848618/36320217-702456c8-1313-11e8-8f25-355601efeea7.png)

**Comment by rncahn** [comment]
Nonetheless, we should follow up your question.  Is the order of the fiber
numbers randomized with respect to location in the petal?

**Comment by sbailey** [comment]
Good catch, @forero.  The fibers numbers are semi-randomized on the focal plane, but clumped in groups of 50 (see DESI-2721 and desimodel fiberpos.fits for details).  If the "assign sky fibers" algorithm is going in order of fiber number, then indeed you could end up with clumps of sky fibers on the focal plane if the science targets aren't very dense.

I don't want to introduce a random number generator into fiberassign, but perhaps you could do a loop like the following to try to assign one sky per bundle before looping back:
```
for i in range(25):
    for j in range(0, 5000, 25):
        # try to assign a sky or std to fiber i+j
```

**Comment by forero** [comment]
@rncahn In the meantime I've just pushed a change where all the unused fibers are filled with sky locations. This seems to work in the tests I've run. Can you please double check I am not doing something crazy?
