### ISSUE TITLE
don't downcast RA,dec to single precision

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#87]
Somewhere in fiberassign, RA and dec are being downcast to single precision instead of double precision.  They are upcast again to double precision before writing the output files, but the resulting RA,dec in the tile files differs from the input MTL file due to the float64 -> float32 -> float64 rounding.  The differences are big enough to matter, both for the precision of placing a fiber and for bookkeeping details like calculating which healpix a target belongs to.

**Comment by rncahn** [comment]
Good
Bob
