### ISSUE TITLE
create separate files of standard stars and sky fibers

### ISSUE THREAD

**Issue by rncahn** [desihub/fiberassign#9]
Other users shouldn't have to create their own collections of standard stars and sky fibers.  These lists will actually be just a collection of randoms.  The density of the standard stars will be kept at 140/sq deg, but the sky fiber density will be increased beyond the current 1400/sq deg.  This gives an average of 2.1/fiber and a likelihood of there being no sky fiber within reach of exp(-2.1)=0.1225.  Daniel Eisenstein suggests increasing this density so that nearly all fibers will have a sky fiber within reach.

**Comment by sbailey** [comment]
To be clear: for current development on mocks, the lists of standard stars and sky fibers can be lists of randoms of appropriate density.  Longer term, both standard stars and sky locations will be an output of target selection.

**Comment by sbailey** [comment]
Implemented sometime prior to newio merge, and updated with MTL format fits files in newio PR #20 .
