### ISSUE TITLE
Checking numbers of stars and sky assigned on tiles

### ISSUE THREAD

**Issue by forero** [desihub/fiberassign#90]
(Comes from #68). We need to extend `qa-fiberassign` to check that each petal have 10 Standard Stars and 40 Sky Fibers.

**Comment by sbailey** [comment]
qa-fiberassign already does this; e.g. from the minitest:
```
/global/cscratch1/sd/sjbailey/desi/dev/end2end/fiberassign/tile_45704.fits - ERROR
  7 unassigned fibers
  Petal 3 has 8/10 stdstars
  Petal 5 has 7/10 stdstars
  Petal 7 has 9/10 stdstars
  Petal 8 has 9/10 stdstars
```
(this tile had all sky fibers needed, but the check is in the code).
