### ISSUE TITLE
Python code to check for collisions

### ISSUE THREAD

**Issue by forero** [desihub/fiberassign#91]
(Comes from #68) We need independent python code that reads the outputs of the C++ code and checks that no positioners are colliding.

**Comment by tskisner** [comment]
I believe that this is fully provided by the `fiberassign.hardware.Hardware` class (returned by `fiberassign.hardware.load_hardware()`).  This class has python methods `check_collisions_xy()` and `check_collisions_thetaphi()` which take a list of positioners and their desired placements and returns a list of booleans indicating which positioners collide.
