### ISSUE TITLE
Guide/Focus/Alignment targets

### ISSUE THREAD

**Issue by forero** [desihub/fiberassign#94]
`fiberassign` should also be able to dump the list of targets that are within reach of the GFA sensors for each tile.

**Comment by sbailey** [comment]
This could also be a separate script, different from the fiberassign executable.  The underlying logic for identifying what objects are on what GFAs is available in `desimodel.focalplane`.  The inputs for this need to be original sweep/tractor files, not target catalogs, because we need to identify every object above a flux limit, not just the objects that passed our targeting cuts.

**Comment by sbailey** [comment]
More details:

`get_gfa_targets(targets, rfluxlim = 1000, tiles = None, buffer_arcsec = 100)` is probably the function you want.  It returns the subset of the targets that are on a GFA and above the flux limit, with two addtional columns for which TILEID and GFA_LOC.  Loop over sweeps, build up the lists, and then filter by TILEID to write the final output files as one file per tile.

**Comment by forero** [comment]
An additional requirement for this script is that it must write down the outputs for individual tiles and the merge them into a multi-HDU fits file including the fiberassign results.

**Comment by forero** [comment]
Here is a version of the script doing the work
https://github.com/forero/SandboxDESI/blob/master/gfa/select_gfa.py

it can be tested using
```bash
python select_gfa.py -o $SCRATCH/gfa_test/ -s /project/projectdirs/cosmo/data/legacysurvey/dr5/sweep/5.0/ -f /project/projectdirs/desi/datachallenge/dr5fiberassign/single_epoch/fiberassign/tileresults
 -t gfa_tiles_mini.txt
```
where `gfa_tiles_mini.txt` can be the following https://github.com/forero/SandboxDESI/blob/master/gfa/gfa_tiles_mini.txt

**Comment by forero** [comment]
Following a discussion with @sbailey and @geordie666  I am filing this issue into `desitarget` and starting a PR there to include the script.
