### ISSUE TITLE
add inner exclusion radius for fiber patrol area

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#98]
Context: Due to the fiber positioner arms having slightly different lengths, there is a region in the center of each positioner that it cannot reach.  Even where it can physically reach, the positioning accuracy may be degraded at the inner-most radii.

Add a parameter for excluding a circle at the center of each positioner (i.e. don't assign targets that land within that circle).  Default initial value 350 microns.  Track this as a separate value per positioner in case we measure this per-positioner.

Here is a plot from @zkdtc showing initial measurements of the inner exclusion radius for 13 positioners:
<img width="314" alt="2018-01-17 4 07 42" src="https://user-images.githubusercontent.com/218471/35074920-13404b36-fba5-11e7-8c83-fe029384754f.png">

**Comment by rncahn** [comment]
Stephen,

300 microns is pretty bad.  That is 1/20 of the 6 mm radius, so we would
miss 1/400 of the area, 12 galaxies per exposure.  But I guess not too bad
when you consider we miss 20% of ELGs.  It would perhaps be more important
for QSOs, but would simply reduce the mean number of exposures for each
Lyman-alpha QSO

**Comment by sbailey** [comment]
An updated analysis from Kai Zhang and Michael Schubnell indicates that the typical inner exclusion radius is more like 100 microns.  That's much better, but we should still have a parameter in fiberassign for this.
![r1minusr2abs](https://user-images.githubusercontent.com/218471/35403150-b19b90d8-01b3-11e8-99a4-8675d7d315c1.png)

**Comment by forero** [comment]
This seems to be hardcoded here:

https://github.com/desihub/fiberassign/blob/master/src/collision.cpp#L223-L228

**Comment by sbailey** [comment]
Ideally we would have a parameter file (like fiberpos.fits, perhaps an augmented version of fiberpos.fits) with the arm lengths for each positioner.

**Comment by tskisner** [comment]
Fiberassign now uses the full geometry of the positioners and will not assign targets that cannot be reached for a given set of arm lengths and angle ranges.  Closing.
