### ISSUE TITLE
fiberassign on arbitrary pointings

### ISSUE THREAD

**Issue by forero** [desihub/fiberassign#99]
We need a wrapper that works like "single_pointing_fiberassign --targets targets.fits --telra 15.2 --teldec 13.3 -o blat.fits" that would

* run MTL to convert targets.fits -> mtl.fits
* generate custom tile.fits, features file, etc. and run fiberassign 
* run GFA targets
* merge those together into a multi-HDU FITS file

**Comment by sbailey** [comment]
Most of this was done by PR #115, but let's leave this issue open until the GFA targets have been included in that wrapper too (as an option, not a requirement).

**Comment by sbailey** [comment]
PR #122 added GFA targets; closing this ticket.
